service: admin-management
frameworkVersion: '3'
useDotenv: true
deprecationNotificationMode: error
disabledDeprecations:
  - UNSUPPORTED_CLI_OPTIONS
  - CLI_OPTIONS_SCHEMA_V3
  - CONFIG_VALIDATION_MODE_DEFAULT_V3
  - 
provider:
  name: aws
  endpointType: REGIONAL
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  region: eu-west-2
  versionFunctions: false
  layers: ${ssm:COMMON_LIB_ARN}
  environment:
    COGNITO_USER_POOL_ID: ${ssm:SELLER_COGNITO_USERPOOL_ID}
    COGNITO_SELLER_CLIENT_ID: ${ssm:SELLER_COGNITO_CLIENT_ID}
    REGION: ${ssm:REGION}
    STAGE: ${opt:stage, self:provider.stage}
    DATABASE: ${opt:stage, self:provider.stage}
    MONGODB_NAME: ${opt:stage, self:provider.stage}
    MONGODB_COLLECTION_NAME: ${opt:stage, self:provider.stage}-users
    MONGO_CLIENT: ${ssm:MONGODB_CONNECTION_STRING}
    AUCTION_MONGODB_COLLECTION_NAME: ${opt:stage, self:provider.stage}-auctions
    COGNITO_USER_POOL: ${ssm:SELLER_COGNITO_USERPOOL_NAME}
    SELLERS_TABLE: ${opt:stage, self:provider.stage}-users
    ORDERS_COLLECTION: ${opt:stage, self:provider.stage}-orders
    SUMSUB_SECRET_KEY: ${ssm:SUMSUB_SECRET_KEY}
    SUMSUB_APP_TOKEN: ${ssm:SUMSUB_APP_TOKEN}
    CSV_FILE: ${ssm:CSV_FILE}
    S3_BUCKET:  ${ssm:BUCKET_NAME}
    LOT_COLLECTION_NAME: ${opt:stage, self:provider.stage}-lots
    COUNTER_LOT: ${opt:stage, self:provider.stage}-counters
    REGISTER_AUCTION_COLLECTION: ${opt:stage, self:provider.stage}-register-auction
    CREDIT_CARD_COLLECTION: ${opt:stage, self:provider.stage}-carts
    SUB_DOMAIN_TABLE: ${opt:stage, self:provider.stage}-subdomain
    USERPOOLS_MONGO: ${opt:stage, self:provider.stage}-userpools
    KMS_KEY_ID: ${ssm:KMS_KEY_ID}
    BUYER_EMAIL_OTP_TEMPLATE: 
      Fn::Join:
        - ":"
        - - "arn"
          - "aws"
          - "mobiletargeting"
          - !Ref "AWS::Region"
          - !Ref "AWS::AccountId"
          - "templates/${self:provider.stage}-buyer_email_otp/EMAIL"
       
    ENCRYPTION_SECRET_KEY: ${ssm:ENCRYPTION_SECRET_KEY}
    BUYER_COLLECTION: ${opt:stage, self:provider.stage}-buyers
    RECAPTCHA_KEY: ${ssm:RECAPTCHA_KEY}
    RECAPTCHA_URL: ${ssm:RECAPTCHA_URL}
    CUSTOMER_SESSION_TOKEN_SECRET: ${ssm:CUSTOMER_SESSION_TOKEN_SECRET}
    SES_SENDER_EMAIL_ID: ${ssm:SENDER_EMAIL}
    DEFAULT_SUB_DOMAIN: ${ssm:DEFAULT_SUB_DOMAIN}
    JWT_SECRET_KEY: ${ssm:JWT_SECRET_KEY}
    TEMPLATE_ARN_EMAIL_RESET_PASSWORD:  
      Fn::Join:
        - ":"
        - - "arn"
          - "aws"
          - "mobiletargeting"
          - !Ref "AWS::Region"
          - !Ref "AWS::AccountId"
          - "templates/${self:provider.stage}-buyer_reset_password/EMAIL"
     
   
    BASE_URL_BUYER: ${ssm:DEFAULT_SUB_DOMAIN}
    CDN_LINK: ${ssm:CDN_URL}
    STRIPE_API_KEY: ${ssm:STRIPE_API_KEY}
    SELLER_GOOGLE_PASSWORD: ${ssm:SELLER_GOOGLE_PASSWORD}
    PASSWORD_SECRET_KEY: ${ssm:PASSWORD_SECRET_KEY}
    ADDRESS_COLLECTION: ${opt:stage, self:provider.stage}-address-management
    COGNITO_ADMIN_AUTH_ARN: ${ssm:SELLER_COGNITO_AUTH_ARN}
    ADMIN_COGNITO_CLIENT_ID: ${ssm:ADMIN_COGNITO_CLIENT_ID}
    COGNITO_ADMIN_USER_POOL_ID: ${ssm:SELLER_COGNITO_USERPOOL_ID}
    REDIS_ENDPOINT: ${ssm:REDIS_ENDPOINT}
    
  http:
    cors: true
    authorizers:
      cognito-auth:
        identitySource: $request.header.Authorization
        issuerUrl: https://cognito-idp.${ssm:REGION}.amazonaws.com/${ssm:SELLER_COGNITO_USERPOOL_ID}
        audience: ${ssm:ADMIN_COGNITO_CLIENT_ID}

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - cognito-idp:*
            - ses:*
            - s3:*
            - lambda:*
            - mobiletargeting:*
            - dynamodb:*
            - execute-api:*
          Resource: "*"
 
package:
  patterns:
    - '!./node_modules/**'
    - ./handlers/**
    - ./data/**
    - ./entities/**
    - ./utils/**
    - ./lib/**

custom:
  packageExternal:
    external:
      - '../../lib'
      - '../../entities'
      
  customDomain:
    rest:
      domainName: ${ssm:DOMAIN_NAME}
      stage: ${opt:stage, self:provider.stage}
      basePath: v1/${self:service}
      certificateName: ${ssm:DOMAIN_CERTIFICATE}
      createRoute53Record: true
      securityPolicy: tls_1_2
      endpointType: REGIONAL

  serverlessIfElse:
    - If: '${param:offline, "false"} == true'
      Set:
        provider.environment.MONGO_CLIENT: ${env:MONGODB_CONNECTION_STRING}

functions:   
  list-auction:
    handler: handlers/list_auction.list_auction
    runtime: python3.8
    layers:
    - ${ssm:COMMON_LIB_ARN_PYTHON}
    vpc:
      securityGroupIds:
      - ${ssm:SECURITY_GROUP_ID}
      subnetIds:
      - ${ssm:SUBNET_ID}
    events:
      - http:
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Requested-With
              - Accept
              - Access-Control-Allow-Headers
          path: /auctions
          method: get
          authorizer:
                arn: ${ssm:SELLER_COGNITO_AUTH_ARN}
  list-buyers:
    handler: handlers/list_buyers.list_buyers
    runtime: python3.8
    layers:
    - ${ssm:COMMON_LIB_ARN_PYTHON}
    vpc:
      securityGroupIds:
      - ${ssm:SECURITY_GROUP_ID}
      subnetIds:
      - ${ssm:SUBNET_ID}
    events:
      - http:
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Requested-With
              - Accept
              - Access-Control-Allow-Headers
          path: /buyers
          method: get
          authorizer:
                arn: ${ssm:SELLER_COGNITO_AUTH_ARN}
  list-sellers:
    handler: handlers/list_sellers.list_sellers
    runtime: python3.8
    layers:
    - ${ssm:COMMON_LIB_ARN_PYTHON}
    vpc:
      securityGroupIds:
      - ${ssm:SECURITY_GROUP_ID}
      subnetIds:
      - ${ssm:SUBNET_ID}
    events:
      - http:
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Requested-With
              - Accept
              - Access-Control-Allow-Headers
          path: /sellers
          method: get
          authorizer:
                arn: ${ssm:SELLER_COGNITO_AUTH_ARN}
  buyer-details:
    handler: handlers/buyer_detail.buyer_detail
    runtime: python3.8
    layers:
    - ${ssm:COMMON_LIB_ARN_PYTHON}
    vpc:
      securityGroupIds:
      - ${ssm:SECURITY_GROUP_ID}
      subnetIds:
      - ${ssm:SUBNET_ID}
    events:
      - http:
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Requested-With
              - Accept
              - Access-Control-Allow-Headers
          path: /buyer-details
          method: get
          authorizer:
                arn: ${ssm:SELLER_COGNITO_AUTH_ARN}
  buyer-view-auction:
    handler: handlers/buyer_list_auction.buyer_list_auction
    runtime: python3.8
    layers:
    - ${ssm:COMMON_LIB_ARN_PYTHON}
    vpc:
      securityGroupIds:
      - ${ssm:SECURITY_GROUP_ID}
      subnetIds:
      - ${ssm:SUBNET_ID}
    events:
      - http:
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Requested-With
              - Accept
              - Access-Control-Allow-Headers
          path: /buyer-auctions
          method: get
          authorizer:
                arn: ${ssm:SELLER_COGNITO_AUTH_ARN}
  purchase-list:
    handler: handlers/list_purchases.list_purchases
    runtime: python3.8
    layers:
    - ${ssm:COMMON_LIB_ARN_PYTHON}
    vpc:
      securityGroupIds:
      - ${ssm:SECURITY_GROUP_ID}
      subnetIds:
      - ${ssm:SUBNET_ID}
    events:
      - http:
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Requested-With
              - Accept
              - Access-Control-Allow-Headers
          path: /{id}
          method: get
          authorizer:
                arn: ${ssm:SELLER_COGNITO_AUTH_ARN}
  clone_auction:
    handler: handlers/clone_auction.clone_auction
    runtime: python3.8
    layers:
    - ${ssm:COMMON_LIB_ARN_PYTHON}
    vpc:
      securityGroupIds:
      - ${ssm:SECURITY_GROUP_ID}
      subnetIds:
      - ${ssm:SUBNET_ID}
    events:
      - http:
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Requested-With
              - Accept
              - Access-Control-Allow-Headers
          path: /clone-auction
          method: post
          authorizer:
                arn: ${ssm:SELLER_COGNITO_AUTH_ARN}
  order-details:
    handler: handlers/order_details.order_detail
    runtime: python3.8
    layers:
    - ${ssm:COMMON_LIB_ARN_PYTHON}
    vpc:
      securityGroupIds:
      - ${ssm:SECURITY_GROUP_ID}
      subnetIds:
      - ${ssm:SUBNET_ID}
    events:
      - http:
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Requested-With
              - Accept
              - Access-Control-Allow-Headers
          path: /order-details
          method: get
          authorizer:
                arn: ${ssm:SELLER_COGNITO_AUTH_ARN}

  auction-purchases:
    handler: handlers/auction_purchases.list_purchases
    runtime: python3.8
    layers:
    - ${ssm:COMMON_LIB_ARN_PYTHON}
    vpc:
      securityGroupIds:
      - ${ssm:SECURITY_GROUP_ID}
      subnetIds:
      - ${ssm:SUBNET_ID}
    events:
      - http:
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Requested-With
              - Accept
              - Access-Control-Allow-Headers
          path: /auction-purchases
          method: get
          authorizer:
                arn: ${ssm:SELLER_COGNITO_AUTH_ARN}


resources:
   Resources:
     GatewayResponseDefault4XX:
       Type: 'AWS::ApiGateway::GatewayResponse'
       Properties:
         ResponseParameters:
           gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
           gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
         ResponseType: DEFAULT_4XX
         RestApiId:
           Ref: 'ApiGatewayRestApi'

plugins:
  - serverless-offline
  - serverless-package-external
  - serverless-domain-manager
  - serverless-plugin-ifelse