parameters:
  - name: envName
    type: string

jobs:
    - deployment: Bidding_Deployment_One
      condition: and(contains(variables['build.SourceBranch'], 'bidding-engine'), succeeded())
      displayName: Deployment
      environment: ${{ parameters.envName }}
      pool:
        vmImage: "ubuntu-22.04"
      steps:
        - checkout: self
        - task: Cache@2
          inputs:
            key: 'npmV2 | "$(Agent.OS)" | package.json'
            restoreKeys: |
              npmV2 | "$(Agent.OS)"
            path: "$(System.DefaultWorkingDirectory)/node_modules"
            cacheHitVar: CACHE_RESTORED
          displayName: Cache npm
        - task: DownloadPipelineArtifact@2
          name: environment
          inputs:
            artifact: environment
            targetPath: '$(System.DefaultWorkingDirectory)'
        - script: npm config set registry https://registry.npmmirror.com
        - script: |
            npm install --cache .npm
          condition: ne(variables.CACHE_RESTORED, 'true')
        - script: |
            bash devops/deployment.sh
            if [ $? -ne 0 ]; then
              echo "API testing failed"
              exit 1
            fi
          displayName: 'Deployment'