parameters:
  - name: envName
    type: string

jobs:
    - deployment: Deployment
      condition: and(or(contains(variables['build.SourceBranch'], 'qa'), contains(variables['build.SourceBranch'], 'master'), contains(variables['build.SourceBranch'], 'pre-prod')), succeeded())
      displayName: Deployment
      environment: ${{ parameters.envName }}
      pool:
        vmImage: "ubuntu-22.04"
      strategy:
        # Default deployment strategy, more coming...
        runOnce:
          deploy:
            steps:
              - checkout: self
              - task: Cache@2
                inputs:
                  key: 'npmV2 | "$(Agent.OS)" | package.json'
                  restoreKeys: |
                    npmV2 | "$(Agent.OS)"
                  path: "$(System.DefaultWorkingDirectory)/node_modules"
                  cacheHitVar: CACHE_RESTORED
                displayName: Cache npm
              # - task: DownloadPipelineArtifact@2
              #   name: environment
              #   inputs:
              #     artifact: environment
              #     targetPath: '$(System.DefaultWorkingDirectory)'
              - script: npm config set registry https://registry.npmmirror.com
              - script: |
                  npm install --cache .npm
                condition: ne(variables.CACHE_RESTORED, 'true')
              - bash: |                 
                 wget https://rolesanywhere.amazonaws.com/releases/1.0.3/X86_64/Linux/aws_signing_helper; 
                 chmod +x aws_signing_helper
                displayName: Install AWS Signer

              - task: DownloadSecureFile@1
                name: Certificate
                displayName: 'Download certificate'
                inputs:
                  secureFile: 'certificate.crt'

              - task: DownloadSecureFile@1
                name: Privatekey
                displayName: 'Download private key'
                inputs:
                  secureFile: 'private.key'

              - bash: |
                  aws configure set credential_process "$(pwd)/aws_signing_helper credential-process --certificate $(Certificate.secureFilePath) --private-key $(Privatekey.secureFilePath) --trust-anchor-arn $(TRUSTANCHORARN) --profile-arn $(PROFILEARN) --role-arn $(ROLEARN)" --profile indyauction-pre-production

                  echo "##vso[task.setvariable variable=AWS_SDK_LOAD_CONFIG;]1"  
                displayName: Obtain AWS Credentials

              # - task: AWSCLI@1
              #   displayName: Check AWS identity
              #   inputs:
              #     regionName: 'eu-west-2'
              #     awsCommand: 'sts'
              #     awsSubCommand: 'get-caller-identity'
              - script: |
                  export AWS_REGION=eu-west-2
                  bash devops/terraform_run.sh
                  if [ $? -ne 0 ]; then
                    echo "API testing failed"
                    exit 1
                  fi
                displayName: 'Deployment'