service: auctions
frameworkVersion: '3'
useDotenv: true
deprecationNotificationMode: error
disabledDeprecations:
  - UNSUPPORTED_CLI_OPTIONS
  - CLI_OPTIONS_SCHEMA_V3
  - CONFIG_VALIDATION_MODE_DEFAULT_V3
  - 
provider:
  name: aws
  endpointType: REGIONAL
  runtime: nodejs14.x
  stage: ${opt:stage, 'dev'}
  region: eu-west-2
  versionFunctions: false
  vpc:
    securityGroupIds:
      - ${ssm:SECURITY_GROUP_ID}
    subnetIds:
      - ${ssm:SUBNET_ID}

  layers: ${ssm:COMMON_LIB_ARN}
  environment:
    TABLE_NAME: ${opt:stage, self:provider.stage}-${self:service}
    COGNITO_USER_POOL_ID: ${ssm:SELLER_COGNITO_USERPOOL_ID}
    COGNITO_SELLER_CLIENT_ID: ${ssm:SELLER_COGNITO_CLIENT_ID}
    REGION: ${ssm:REGION}
    STAGE: ${opt:stage, self:provider.stage}
    DATABASE: ${opt:stage, self:provider.stage}
    MONGODB_NAME: ${opt:stage, self:provider.stage}
    MONGODB_COLLECTION_NAME: ${opt:stage, self:provider.stage}-users
    MONGO_CLIENT: ${ssm:MONGODB_CONNECTION_STRING}
    AUCTION_MONGODB_COLLECTION_NAME: ${opt:stage, self:provider.stage}-auctions
    COGNITO_USER_POOL: ${ssm:SELLER_COGNITO_USERPOOL_NAME}
    SELLERS_TABLE: ${opt:stage, self:provider.stage}-users
    SUMSUB_SECRET_KEY: ${ssm:SUMSUB_SECRET_KEY}
    SUMSUB_APP_TOKEN: ${ssm:SUMSUB_APP_TOKEN}
    CSV_FILE: ${ssm:CSV_FILE}
    S3_BUCKET: ${ssm:BUCKET_NAME}
    LOT_COLLECTION_NAME: ${opt:stage, self:provider.stage}-lots
    COUNTER_LOT: ${opt:stage, self:provider.stage}-counters
    CDN_LINK: ${ssm:CDN_URL}
    BID_INFORMATION_COLLECTION: ${opt:stage, self:provider.stage}-bid-informations
    STATE_MACHINE_LOT_ARN:  ${ssm:STATE_MACHINE_LOT_ARN}
    REDIS_URL: ${ssm:REDIS_URL}
    BUYERS_TABLE: ${opt:stage, self:provider.stage}-buyers
    CARTTABLE: ${opt:stage, self:provider.stage}-carts
    SQS_QUEUE_ARN: ${ssm:SQS_QUEUE_ARN}
    QUEUE_URL: https://sqs.eu-west-2.amazonaws.com/${AWS::AccountId}/auto-completion-email-${opt:stage}.fifo
    BIDINFORMATIONTABLE: ${opt:stage, self:provider.stage}-bid-informations
    SQS_QUEUE_NAME: auto-completion-email-${opt:stage, self:provider.stage}.fifo
    UNIQUE_BIDDERS_COLLECTIONS: ${opt:stage, self:provider.stage}-unique-bids
    COMMON_LIB_ARN_PYTHON_2: ${ssm:COMMON_LIB_ARN_PYTHON_2}
    STEP_FUNCTION_ARN_TABLE: ${opt:stage, self:provider.stage}-step-function-arns
    REDIS_ENDPOINT: ${ssm:REDIS_ENDPOINT}
    SOCKET_URL: ${ssm:SOCKET_URL}
    TEMPLATE_ARN_AUCTION_COMPLETION:
      Fn::Join:
        - ":"
        - - "arn"
          - "aws"
          - "mobiletargeting"
          - !Ref "AWS::Region"
          - !Ref "AWS::AccountId"
          - "templates/${self:provider.stage}-send-auction-completion-email/EMAIL"
    S3_BUCKET_URL:  https://qa-cdn.indyauction.net/public
    SENDER_EMAIL: ${ssm:SENDER_EMAIL}

    
    
  http:
    cors: true
     


  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - cognito-idp:*
            - ses:*
            - s3:*
            - sqs:*
            - states:*
            - sts:*
            - lambda:*
            - mobiletargeting:*
          Resource: "*"
 
package:
  patterns:
    - '!./node_modules/**'
    - ./handlers/**
    - ./data/**
    - ./entities/**
    - ./utils/**
    - ./lib/**


stepFunctions:
  stateMachines:
    lot-published:
      name: ${opt:stage}-lot-published
      definition:
        Comment: "Step function will trigger when lot published"
        StartAt: wait-for-auction-start
        States:
          wait-for-auction-start:
            Type: Wait
            TimestampPath: "$.start_date"
            Next:  process-cache-lots
          process-cache-lots:
            Type: Task
            Resource:
              Fn::GetAtt: ["save-to-cache", Arn]
            Next: check-lot-ends
          check-lot-ends:
              Type: Wait
              TimestampPath: "$.end_date"
              Next:  process-cart
          process-cart:
              Type: Task
              Resource:
                Fn::GetAtt: ["process-cart", Arn]
              End: true

    # auction-ended:
    #  name: ${opt:stage}-auction-ended
    #  definition:
    #     Comment: "Step function will trigger when auction ended"
    #     StartAt: check-auction-ends
    #     States:
    #       check-auction-ends:
    #             Type: Wait
    #             TimestampPath: "$.end_date"
    #             Next: process-next-steps
    #       process-next-steps:
    #         Type: Task
    #         Resource:
    #           Fn::GetAtt: ["send-email_auction", Arn]
    #         End: true
        

custom:
  packageExternal:
    external:
      - '../../lib'
      - '../../entities'
      
  customDomain:
    rest:
      domainName: ${ssm:DOMAIN_NAME}
      stage: ${opt:stage, self:provider.stage}
      basePath: v1/${self:service}
      certificateName: ${ssm:DOMAIN_CERTIFICATE}
      createRoute53Record: true
      securityPolicy: tls_1_2
      endpointType: REGIONAL

  serverlessIfElse:
    - If: '${param:offline, "false"} == true'
      Set:
        provider.environment.MONGO_CLIENT: ${env:MONGODB_CONNECTION_STRING}

functions: 

  create:
    handler: handlers/create.create_auction
    layers:
      - ${ssm:COMMON_LIB_ARN}
    events:
      - http:
          cors: true
          path: /
          method: post
          authorizer:
              arn: ${ssm:SELLER_COGNITO_AUTH_ARN}
    
  list_auction:
      handler: handlers/list.list_auction
      runtime: python3.8
      memorySize: 128
      layers:
        - ${ssm:COMMON_LIB_ARN_PYTHON}
      events:
        - http:
            cors: true
            path: /
            method: get
            authorizer:
                arn: ${ssm:SELLER_COGNITO_AUTH_ARN}
  
  delete_note:
      handler: handlers/delete_note.delete_note
      runtime: python3.8
      memorySize: 128
      layers:
        - ${ssm:COMMON_LIB_ARN_PYTHON}
      events:
        - http:
            cors: true
            path: /
            method: patch
            authorizer:
                arn: ${ssm:SELLER_COGNITO_AUTH_ARN}
  
  create_lots:
    handler: handlers/create_lots.lambda_handler
    runtime: python3.8
    layers:
      - ${ssm:COMMON_LIB_ARN_PYTHON}
    events:
      - http:
          cors: true
          path: /lots
          method: post
          authorizer:
              arn: ${ssm:SELLER_COGNITO_AUTH_ARN}
            
  list_lots:
    handler: handlers/view_lots.list_lots
    runtime: python3.8
    layers:
      - ${ssm:COMMON_LIB_ARN_PYTHON}
    events:
      - http:
          cors: true
          path: /lots
          method: get
          authorizer:
              arn: ${ssm:SELLER_COGNITO_AUTH_ARN}
 
  admin_list_lots:
    handler: handlers/admin_list_lots.list_lots
    runtime: python3.8
    layers:
      - ${ssm:COMMON_LIB_ARN_PYTHON}
    events:
      - http:
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Requested-With
              - Accept
              - Requestid
              - Access-Control-Allow-Header
          path: /admin/lots
          method: get
          authorizer:
            arn: ${ssm:SELLER_COGNITO_AUTH_ARN}

  delete_lot:
      handler: handlers/delete_lot.delete_lot
      runtime: python3.8
      memorySize: 128
      layers:
        - ${ssm:COMMON_LIB_ARN_PYTHON}
      events:
        - http:
            cors: true
            path: /lots
            method: delete
            authorizer:
                arn: ${ssm:SELLER_COGNITO_AUTH_ARN}

  reorder_lot:
      handler: handlers/reorder_lots.lambda_handler
      runtime: python3.8
      memorySize: 128
      layers:
        - ${ssm:COMMON_LIB_ARN_PYTHON}
      events:
        - http:
            cors: true
            path: /reorder-lots
            method: post
            authorizer:
                arn: ${ssm:SELLER_COGNITO_AUTH_ARN}
    
  clone_auction:
      handler: handlers/clone_auction.clone_auction
      runtime: python3.8
      memorySize: 128
      layers:
        - ${ssm:COMMON_LIB_ARN_PYTHON}
      events:
        - http:
            cors: true
            path: /clone
            method: post
            authorizer:
                arn: ${ssm:SELLER_COGNITO_AUTH_ARN}

  view:
    handler: handlers/view.view
    runtime: python3.8
    layers:
      - ${ssm:COMMON_LIB_ARN_PYTHON}
    events:
      - http:
          cors: true
          path: /view
          method: get
          authorizer:
              arn: ${ssm:SELLER_COGNITO_AUTH_ARN}

  update_lot:
      handler: handlers/update_lot.update
      runtime: python3.8
      memorySize: 128
      layers:
        - ${ssm:COMMON_LIB_ARN_PYTHON}
      events:
        - http:
            cors: true
            path: /lots
            method: patch
            authorizer:
                arn: ${ssm:SELLER_COGNITO_AUTH_ARN}

  import_lots:
    handler: handlers/import_lots.import_lots
    runtime: python3.8
    layers:
      - ${ssm:COMMON_LIB_ARN_PYTHON}
    events:
      - http:
          cors: true
          path: /import
          method: post
          authorizer:
              arn: ${ssm:SELLER_COGNITO_AUTH_ARN}

  update_auction:
      handler: handlers/update.update_auction
      runtime: python3.8
      memorySize: 128
      layers:
        - ${ssm:COMMON_LIB_ARN_PYTHON}
        - ${ssm:COMMON_LIB_ARN_PYTHON_2}
      events:
        - http:
            cors: true
            path: /update/{auction_id}
            method: patch
            authorizer:
                arn: ${ssm:SELLER_COGNITO_AUTH_ARN}

  delete_auction:
      handler: handlers/delete.delete_auction
      runtime: python3.8
      memorySize: 128
      layers:
        - ${ssm:COMMON_LIB_ARN_PYTHON}
      events:
        - http:
            cors: true
            path: /{auction_id}
            method: delete
            authorizer:
                arn: ${ssm:SELLER_COGNITO_AUTH_ARN}

  deactivate:
    handler: handlers/deactivate.deactivate
    runtime: python3.8
    layers:
      - ${ssm:COMMON_LIB_ARN_PYTHON}
    events:
      - http:
          cors: true
          path: /deactivate
          method: post
          authorizer:
              arn: ${ssm:SELLER_COGNITO_AUTH_ARN}

  process-cart:
    handler: handlers/add_to_cart.handler
    layers:
      - ${ssm:COMMON_LIB_ARN}

  send-email_auction:
    handler: handlers/auto_completion_bid.handler
    layers:
      - ${ssm:COMMON_LIB_ARN}

  save-to-cache:
    handler: handlers/save_to_cache.handler
    layers:
      - ${ssm:COMMON_LIB_ARN}
      
  sqs-trigger-function:
    handler: handlers/sqs_trigger_function.sqsTriggerFunction
    layers:
      - ${ssm:COMMON_LIB_ARN}
    events:
      - sqs: ${ssm:SQS_QUEUE_ARN}

  wait-for-lot-ends:
    handler: handlers/wait_for_lot_ends.handler
    layers:
      - ${ssm:COMMON_LIB_ARN}
  

resources:
  Resources:

    GatewayResponseDefault4XX:
       Type: 'AWS::ApiGateway::GatewayResponse'
       Properties:
         ResponseParameters:
           gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
           gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
         ResponseType: DEFAULT_4XX
         RestApiId:
           Ref: 'ApiGatewayRestApi'
    


plugins:
  - serverless-offline
  - serverless-package-external
  - serverless-domain-manager
  - serverless-plugin-ifelse
  - serverless-step-functions