service: auctions
frameworkVersion: '3'
useDotenv: true
deprecationNotificationMode: error
disabledDeprecations:
  - UNSUPPORTED_CLI_OPTIONS
  - CLI_OPTIONS_SCHEMA_V3
  - CONFIG_VALIDATION_MODE_DEFAULT_V3
  - 
provider:
  name: aws
  endpointType: REGIONAL
  runtime: nodejs14.x
  stage: ${opt:stage, 'dev'}
  region: ${env:REGION}
  versionFunctions: false
  vpc:
    securityGroupIds:
      - sg-0882c1da39e729097
    subnetIds:
      - subnet-0ff05c7c2bd2a3f87
  layers: ${env:COMMON_LIB_ARN}
  environment:
    TABLE_NAME: ${opt:stage, self:provider.stage}-${self:service}
    COGNITO_USER_POOL_ID: ${env:COGNITO_USER_POOL_ID}
    COGNITO_SELLER_CLIENT_ID: ${env:COGNITO_SELLER_CLIENT_ID}
    REGION: ${env:REGION}
    STAGE: ${opt:stage, self:provider.stage}
    DATABASE: ${env:DATABASE}
    MONGODB_NAME: ${env:MONGODB_NAME}
    MONGODB_COLLECTION_NAME: ${env:MONGODB_COLLECTION_NAME}
    MONGO_CLIENT: ${env:MONGO_CLIENT}
    AUCTION_MONGODB_COLLECTION_NAME: ${env:AUCTION_MONGODB_COLLECTION_NAME}
    COGNITO_USER_POOL: ${env:COGNITO_USER_POOL}
    SELLERS_TABLE: ${opt:stage, self:provider.stage}-users
    SUMSUB_SECRET_KEY: ${env:SUMSUB_SECRET_KEY}
    SUMSUB_APP_TOKEN: ${env:SUMSUB_APP_TOKEN}
    CSV_FILE: ${env:CSV_FILE}
    S3_BUCKET: ${env:S3_BUCKET}
    LOT_COLLECTION_NAME: ${env:LOT_COLLECTION_NAME}
    COUNTER_LOT: ${env:COUNTER_LOT}
    CDN_LINK: ${env:CDN_LINK}
    BID_INFORMATION_COLLECTION: ${env:BID_INFORMATION_COLLECTION}
    STATE_MACHINE_LOT_ARN:  arn:aws:states:eu-west-2:929441721738:stateMachine:${opt:stage, self:provider.stage}-lot-published
    REDIS_URL: ${env:REDIS_URL}
    STATE_MACHINE_AUCTION_ARN: ${env:STATE_MACHINE_AUCTION_ARN}
    BUYERS_TABLE: ${opt:stage, self:provider.stage}-buyers
    CARTTABLE: ${opt:stage, self:provider.stage}-carts
    SQS_QUEUE_ARN: arn:aws:sqs:eu-west-2:929441721738:auto-completion-email-${opt:stage, self:provider.stage}.fifo
    QUEUE_URL: 'https://sqs.eu-west-2.amazonaws.com/929441721738/auto-completion-email-${opt:stage, self:provider.stage}.fifo'
    BIDINFORMATIONTABLE: ${opt:stage, self:provider.stage}-bid-informations
    SQS_QUEUE_NAME: auto-completion-email-${opt:stage, self:provider.stage}.fifo
    UNIQUE_BIDDERS_COLLECTIONS: ${opt:stage, self:provider.stage}-unique-bids
    STEP_FUNCTION_ARN_TABLE: ${opt:stage, self:provider.stage}-step-function-arns
    
    
  http:
    cors: true
    authorizers:
      cognito-auth:
        identitySource: $request.header.Authorization
        issuerUrl: https://cognito-idp.${env:REGION}.amazonaws.com/${env:COGNITO_USER_POOL_ID}
        audience: ${env:COGNITO_SELLER_CLIENT_ID}


  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - cognito-idp:*
            - ses:*
            - s3:*
            - sqs:*
            - states:*
            - sts:*
            - lambda:*
            - mobiletargeting:*
          Resource: "*"
 
package:
  patterns:
    - '!./node_modules/**'
    - ./handlers/**
    - ./data/**
    - ./entities/**
    - ./utils/**
    - ./lib/**


stepFunctions:
  stateMachines:
    lot-published:
      name: ${opt:stage}-lot-published
      definition:
        Comment: "Step function will trigger when lot published"
        StartAt: wait-for-auction-start
        States:
          wait-for-auction-start:
            Type: Wait
            TimestampPath: "$.start_date"
            Next:  process-cache-lots
          process-cache-lots:
            Type: Task
            Resource:
              Fn::GetAtt: ["save-to-cache", Arn]
            Next: check-lot-ends
          check-lot-ends:
              Type: Wait
              TimestampPath: "$.end_date"
              Next:  process-cart
          process-cart:
              Type: Task
              Resource:
                Fn::GetAtt: ["process-cart", Arn]
              End: true

    # auction-ended:
    #  name: ${opt:stage}-auction-ended
    #  definition:
    #     Comment: "Step function will trigger when auction ended"
    #     StartAt: check-auction-ends
    #     States:
    #       check-auction-ends:
    #             Type: Wait
    #             TimestampPath: "$.end_date"
    #             Next: process-next-steps
    #       process-next-steps:
    #         Type: Task
    #         Resource:
    #           Fn::GetAtt: ["send-email_auction", Arn]
    #         End: true
        

custom:
  packageExternal:
    external:
      - '../../lib'
      - '../../entities'
      
  customDomain:
    rest:
      domainName: ${env:DOMAIN_NAME}
      stage: ${opt:stage, self:provider.stage}
      basePath: ${opt:stage, self:provider.stage}/v1/${self:service}
      certificateName: ${env:DOMAIN_CERTIFICATE}
      createRoute53Record: true
      securityPolicy: tls_1_2
      endpointType: REGIONAL

functions: 

  create:
    handler: handlers/create.create_auction
    layers:
      - ${env:COMMON_LIB_ARN}
    events:
      - http:
          cors: true
          path: /
          method: post
          authorizer:
              arn: ${env:COGNITO_AUTH_ARN}
    
  list_auction:
      handler: handlers/list.list_auction
      runtime: python3.8
      memorySize: 128
      layers:
        - ${env:PYTHON_LIB_ARN}
      events:
        - http:
            cors: true
            path: /
            method: get
            authorizer:
                arn: ${env:COGNITO_AUTH_ARN}
  
  delete_note:
      handler: handlers/delete_note.delete_note
      runtime: python3.8
      memorySize: 128
      layers:
        - ${env:PYTHON_LIB_ARN}
      events:
        - http:
            cors: true
            path: /
            method: patch
            authorizer:
                arn: ${env:COGNITO_AUTH_ARN}
  
  create_lots:
    handler: handlers/create_lots.lambda_handler
    runtime: python3.8
    layers:
      - ${env:PYTHON_LIB_ARN}
    events:
      - http:
          cors: true
          path: /lots
          method: post
          authorizer:
              arn: ${env:COGNITO_AUTH_ARN}
            
  list_lots:
    handler: handlers/view_lots.list_lots
    runtime: python3.8
    layers:
      - ${env:PYTHON_LIB_ARN}
    events:
      - http:
          cors: true
          path: /lots
          method: get
          authorizer:
              arn: ${env:COGNITO_AUTH_ARN}

  # admin-list_lots:
  #   handler: handlers/view_lots.list_lots
  #   runtime: python3.8
  #   layers:
  #     - ${env:PYTHON_LIB_ARN}
  #   events:
  #     - http:
  #         cors: true
  #         path: /admin/lots
  #         method: get
  #         authorizer:
  #             arn: ${env:COGNITO_AUTH_ARN}
  
  admin_list_lots:
    handler: handlers/admin_list_lots.list_lots
    runtime: python3.8
    layers:
      - ${env:PYTHON_LIB_ARN}
    events:
      - http:
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Requested-With
              - Accept
              - Requestid
              - Access-Control-Allow-Header
          path: /admin/lots
          method: get
          authorizer:
            arn: ${env:COGNITO_AUTH_ARN}

  delete_lot:
      handler: handlers/delete_lot.delete_lot
      runtime: python3.8
      memorySize: 128
      layers:
        - ${env:PYTHON_LIB_ARN}
      events:
        - http:
            cors: true
            path: /lots
            method: delete
            authorizer:
                arn: ${env:COGNITO_AUTH_ARN}

  reorder_lot:
      handler: handlers/reorder_lots.lambda_handler
      runtime: python3.8
      memorySize: 128
      layers:
        - ${env:PYTHON_LIB_ARN}
      events:
        - http:
            cors: true
            path: /reorder-lots
            method: post
            authorizer:
                arn: ${env:COGNITO_AUTH_ARN}
    
  clone_auction:
      handler: handlers/clone_auction.clone_auction
      runtime: python3.8
      memorySize: 128
      layers:
        - ${env:PYTHON_LIB_ARN}
      events:
        - http:
            cors: true
            path: /clone
            method: post
            authorizer:
                arn: ${env:COGNITO_AUTH_ARN}

  view:
    handler: handlers/view.view
    runtime: python3.8
    layers:
      - ${env:COMMON_PYTHON_LIB_ARN}
    events:
      - http:
          cors: true
          path: /view
          method: get
          authorizer:
              arn: ${env:COGNITO_AUTH_ARN}

  update_lot:
      handler: handlers/update_lot.update
      runtime: python3.8
      memorySize: 128
      layers:
        - ${env:PYTHON_LIB_ARN}
      events:
        - http:
            cors: true
            path: /lots
            method: patch
            authorizer:
                arn: ${env:COGNITO_AUTH_ARN}

  import_lots:
    handler: handlers/import_lots.import_lots
    runtime: python3.8
    layers:
      - ${env:COMMON_PYTHON_LIB_ARN}
    events:
      - http:
          cors: true
          path: /import
          method: post
          authorizer:
              arn: ${env:COGNITO_AUTH_ARN}

  update_auction:
      handler: handlers/update.update_auction
      runtime: python3.8
      memorySize: 128
      layers:
        - ${env:PYTHON_LIB_ARN}
      events:
        - http:
            cors: true
            path: /update/{auction_id}
            method: patch
            authorizer:
                arn: ${env:COGNITO_AUTH_ARN}

  delete_auction:
      handler: handlers/delete.delete_auction
      runtime: python3.8
      memorySize: 128
      layers:
        - ${env:PYTHON_LIB_ARN}
      events:
        - http:
            cors: true
            path: /{auction_id}
            method: delete
            authorizer:
                arn: ${env:COGNITO_AUTH_ARN}

  deactivate:
    handler: handlers/deactivate.deactivate
    runtime: python3.8
    layers:
      - ${env:COMMON_PYTHON_LIB_ARN}
    events:
      - http:
          cors: true
          path: /deactivate
          method: post
          authorizer:
              arn: ${env:COGNITO_AUTH_ARN}

  process-cart:
    handler: handlers/add_to_cart.handler
    layers:
      - arn:aws:lambda:eu-west-2:929441721738:layer:nodejs-indy-auction:12


  save-to-cache:
    handler: handlers/save_to_cache.handler
    layers:
      - arn:aws:lambda:eu-west-2:929441721738:layer:nodejs-indy-auction:10
      
  sqs-trigger-function:
    handler: handlers/sqs_trigger_function.sqsTriggerFunction
    layers:
      - ${env:COMMON_LIB_ARN}
    events:
      - sqs:
          arn: arn:aws:sqs:eu-west-2:929441721738:auto-completion-email-${opt:stage, self:provider.stage}.fifo

  wait-for-lot-ends:
    handler: handlers/wait_for_lot_ends.handler
    layers:
      - ${env:COMMON_LIB_ARN}
  

resources:
  Resources:
    messageQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: auto-completion-email-${opt:stage, self:provider.stage}.fifo
        FifoQueue: true
    GatewayResponseDefault4XX:
       Type: 'AWS::ApiGateway::GatewayResponse'
       Properties:
         ResponseParameters:
           gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
           gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
         ResponseType: DEFAULT_4XX
         RestApiId:
           Ref: 'ApiGatewayRestApi'

plugins:
  - serverless-offline
  - serverless-package-external
  - serverless-domain-manager
  - serverless-step-functions