image: node:latest
clone:
  depth: full
 #max time in minutes
definitions:
  caches:
    sonar: ~/.sonar/cache
  services:
    docker-high-memory:
      memory: 7128
      type: docker

  steps:
    - step: &BuildStep
        name: Build
        image: sleavely/node-awscli:14.x
        caches:
          - node
        script:
          - if [ "$BITBUCKET_PR_DESTINATION_BRANCH" == staging ]; then exit 0 ; fi
          - printenv | awk -F= '!/^HOME|^PWD/ {print $1 "=\""$2"\""}' >> .env
          - ./envs.sh
          - npm install
          - echo "Build"
        artifacts:
          - .env

    - step: &ESlint
        name: ESLint
        script:
           - echo "ESLint"
           - if [ "$BITBUCKET_PR_DESTINATION_BRANCH" == staging ]; then exit 0 ; fi
           - npm install eslint
           - npm run eslint

    - step: &Pylint
        name: PyLint
        image: python:3.9   # Choose the desired Python version
        script:
            - echo "Pylint is skipped"
            - if [ "$BITBUCKET_PR_DESTINATION_BRANCH" == staging ]; then exit 0 ; fi
            - apt-get update   # Update package manager (for Debian/Ubuntu-based images)
            - apt-get install -y python3-pip   # Install pip (for Debian/Ubuntu-based images)
            - pip install pylint
            - pylint services/**/**/*.py

    - step: &LicenseCompliance
        name: License Compliance
        script:
          - if [ "$BITBUCKET_PR_DESTINATION_BRANCH" == staging ]; then exit 0 ; fi
          - echo "License Compliance"
          - npm i --force
          - npm install -g license-checker
          - license-checker --json > licenses.json  
          - node license.js
        artifacts:
          - matching_licenses.json
          - licenses.json


    - step: &DependencyScanning
        name: Dependency Scanning
        services:
          - docker
        script:
          - echo "Dependency Scanning"
        #   - pipe: docker://aligent/owasp-dependency-check-pipe
        #     variables:
        #       SCAN_PATH: "./package.json"
        #       CVSS_FAIL_LEVEL: "1"
        # artifacts:
        #   - test-results/**  


    - step: &SecretChecking
        name: Secret Detection
        script:
          - echo "Secret Checking"
          - if [ "$BITBUCKET_PR_DESTINATION_BRANCH" == staging ]; then exit 0 ; fi
          - pipe: atlassian/git-secrets-scan:0.4.3

    - step: &SAST
        name: Static Application Security Testing (SAST)
        image: python:latest
        script:
          - echo "SAST"
          - if [ "$BITBUCKET_PR_DESTINATION_BRANCH" == staging ]; then exit 0 ; fi
          - apt-get update && apt-get install python-is-python3 -y && apt-get install python3-pip -y
          - pip install pip==23.2.1 --break-system-packages
          - pip3 install njsscan
          - njsscan -w .
          - pip install bandit
          - bandit -r services/**/*.py


    - step: &Deploy
        name: Deployment
        size: 2x
        script:
          - echo "Deploy"
          - npm i -g serverless@3.15.2
          - npm i -g @serverless/compose
          - npm i serverless-aws-documentation
          - npm i serverless-domain-manager --f
          - npm i serverless-dynamodb-autoscaling
          - npm i serverless-dynamodb-ttl
          - npm i serverless-offline
          - npm i serverless-package-external
          - npm i serverless-python-requirements
          - npm i serverless-appsync-plugin
          - apt-get update && apt-get install python -y && apt-get install python3-pip -y
          - export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
          - export AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
          - export AWS_REGION=${REGION}
          - sls deploy --stage ${STAGE} --max-concurrency 5
        after-script:
          - apt-get update && apt-get install python-is-python3 -y && apt-get install python3-pip -y
          - pip install pip==23.2.1 --break-system-packages
          - pip3 install requests
          - python deployment.py
      
    - step: &DevDeploy
        name: Deployment
        size: 2x
        script:
          - echo "Deploy"
          # - pipe: atlassian/aws-code-deploy:1.4.0
          #   variables:
          #     AWS_DEFAULT_REGION: $AWS_REGION
          #     AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
          #     AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
          #     APPLICATION_NAME: $APPLICATION_NAME
          #     DEPLOYMENT_GROUP: $DEPLOYMENT_GROUP
          #     S3_BUCKET: $S3_BUCKET
          #     COMMAND: 'deploy'
          #     WAIT: 'true'
          #     # VERSION_LABEL: 'my-app-1.0.0'
          #     IGNORE_APPLICATION_STOP_FAILURES: 'true'
          #     FILE_EXISTS_BEHAVIOR: 'OVERWRITE'
    
    - step: &TerraDeploy
        name: Deployment
        size: 2x
        script:
          - apt-get update && apt-get install -y gnupg software-properties-common
          - wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | tee /usr/share/keyrings/hashicorp-archive-keyring.gpg
          - gpg --no-default-keyring --keyring /usr/share/keyrings/hashicorp-archive-keyring.gpg --fingerprint
          - echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/hashicorp.list
          - apt update
          - apt-get install terraform
          - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          - unzip -u awscliv2.zip
          - ./aws/install
          - bash devops/terraform_run.sh


    
    - step: &APITesting 
        name: API Test Automation
        script:
          - if [ "$BITBUCKET_PR_DESTINATION_BRANCH" == staging ]; then exit 0 ; fi
          - echo "API Testing Automation"
          - source .env
          - apt-get update && apt-get install python-is-python3 -y && apt-get install python3-pip -y && apt-get install jq -y
          - export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
          - export AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
          - pip install pip==22.3.1 --break-system-packages
          - pip3 install boto3 dredd_hooks
          - pip3 install python-dotenv
          - pip3 install uuid
          - pip3 install pyjwt
          - pip3 install requests
          - npm i -g dredd
          - ./api-testing.sh
          - ./doc.sh
          - pipe: atlassian/aws-s3-deploy:0.2.4
            variables:
              AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID_MAIN
              AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY_MAIN
              AWS_DEFAULT_REGION: $AWS_REGION
              S3_BUCKET: $DOCS_BUCKET_NAME
              LOCAL_PATH: "swaggerdocs"
          - pipe: atlassian/aws-cloudfront-invalidate:0.1.1
            variables:
              AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID_MAIN
              AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY_MAIN
              AWS_DEFAULT_REGION: $AWS_REGION
              DISTRIBUTION_ID: $DISTRIBUTION_ID  

    - step: &DAST 
        name: Dynamic Application Security Testing (DAST) 
        image: softwaresecurityproject/zap-stable
        services:
          - docker-high-memory
        size: 2x
        script:
          - docker run -u zap -p 8080:8080 -d softwaresecurityproject/zap-stable zap.sh -daemon -host 0.0.0.0 -port 8080 -config api.disablekey=true -config api.addrs.addr.name=.* -config api.addrs.addr.regex=true
          - sleep 30
          - cd $BITBUCKET_CLONE_DIR
          - git config --global --add safe.directory $BITBUCKET_CLONE_DIR
          - pip install boto3
          - pip install PyJWT
          - pip3 install GitPython
          - mkdir test_results
          - python3 dast.py
        artifacts:
          - test_results/**
    

    - step: &Danger
        name: Git Compliance - Danger
        caches:
          - node
        script:
          - if [ "$BITBUCKET_PR_DESTINATION_BRANCH" == staging ]; then exit 0 ; fi
          - export LANG="C.UTF-8"
          - npm install --f
          - npm install -g danger
          - npx danger ci
    
    - step: &DeletePreProduction
        name: Deployment
        size: 2x
        script:
          - apt-get update && apt-get install -y gnupg software-properties-common
          - wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | tee /usr/share/keyrings/hashicorp-archive-keyring.gpg
          - gpg --no-default-keyring --keyring /usr/share/keyrings/hashicorp-archive-keyring.gpg --fingerprint
          - echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/hashicorp.list
          - apt update
          - apt-get install terraform
          - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          - unzip -u awscliv2.zip
          - ./aws/install
          - bash devops/terraform_destroy_init.sh
    
    - step: &runcommands
        script:
          - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          - unzip -u awscliv2.zip
          - ./aws/install
          - echo "Runbook Execution Step!"
          - export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
          - export AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
          - aws s3 sync ${RUNBOOK_PATH} s3://${RUNBOOK_BUCKET}/${RUNBOOK_PATH} --acl public-read
          - aws ssm send-command --targets "Key=instanceids,Values=$(aws ssm get-parameter --name 'EC2_INSTANCE_ID' --query 'Parameter.Value' --output text --region ${REGION})" --document-name 'AWS-RunShellScript' --parameters "commands=['if [ ! -d runbook ]; then mkdir runbook; fi && cd runbook && aws s3 sync s3://${RUNBOOK_BUCKET}/ . && chmod +x ${RUNBOOK_PATH}/* && cd ${RUNBOOK_PATH} && sh main.sh && cd ../../ && rm -r ${RUNBOOK_PATH} && cd .. && rm -r runbook']" --region ${REGION} --cloud-watch-output-config CloudWatchLogGroupName="mongo-restore",CloudWatchOutputEnabled=true



pipelines:
  custom: 
   
    DAST:
      - step: *DAST
    
    CreateDisposableEnvironment:
      - stage:
          name: Testing and Pre-Production Deployment
          deployment: Pre-Production
          image: python:3.7.2
          steps:
            - step: *BuildStep
            - step: *TerraDeploy
    DeleteDisposableEnvironment:
      - stage:
          name: Testing and Pre-Production Deployment
          deployment: Pre-Production
          image: python:3.7.2
          steps:
            - step: *BuildStep
            - step: *DeletePreProduction
    
    RunBookExecutionQA:
      - variables:
        - name: RUNBOOK_PATH
          default: 'runbooks/'
      - stage:
          name: RUNBOOK EXECUTION
          image: python:3.7.2
          deployment: QA
          steps:
            - step: *runcommands
    RunBookExecutionDev:
      - variables:
        - name: RUNBOOK_PATH
          default: 'runbooks/'
      - stage:
          name: RUNBOOK EXECUTION
          image: python:3.7.2
          deployment: Develop
          steps:
            - step: *runcommands
    RunBookExecutionPreProd:
      - variables:
        - name: RUNBOOK_PATH
          default: 'runbooks/'
      - stage:
          name: RUNBOOK EXECUTION
          image: python:3.7.2
          deployment: Pre-Production
          steps:
            - step: *runcommands
    RunBookExecutionProd:
      - variables:
        - name: RUNBOOK_PATH
          default: 'runbooks/'
      - stage:
          name: RUNBOOK EXECUTION
          image: python:3.7.2
          deployment: Production
          steps:
            - step: *runcommands
    
  pull-requests:    
    feature/**:
      - parallel:
          fail-fast: true
          steps:
            - step: *BuildStep
            - step: *Pylint
            - step: *ESlint
            - step: *SAST
            - step: *SecretChecking
            - step: *LicenseCompliance
            - step: *DependencyScanning
            - step: *Danger
      - step: *APITesting
      - step: *DAST
        
      
    bugfix/**:
      - parallel:
          fail-fast: true
          steps:
            - step: *BuildStep
            - step: *Pylint
            - step: *ESlint
            - step: *SAST
            - step: *SecretChecking
            - step: *LicenseCompliance
            - step: *DependencyScanning
            - step: *Danger
      - step: *APITesting
      - step: *DAST

    hotfix/**:
      - parallel:
          fail-fast: true
          steps:
            - step: *BuildStep
            - step: *Pylint
            - step: *ESlint
            - step: *SAST
            - step: *SecretChecking
            - step: *LicenseCompliance
            - step: *DependencyScanning
            - step: *Danger
      - step: *APITesting
      - step: *DAST

  branches:
    qa:
      - parallel:
          fail-fast: true
          steps:
            - step: *BuildStep
            - step: *SecretChecking
      - stage:
            name: QA Deployment
            deployment: QA
            steps:
              - step: *TerraDeploy
    
    Pre-Production:
      - parallel:
          fail-fast: true
          steps:
            - step: *SecretChecking
      - stage:
            name: Pre-Production Deployment
            deployment: Pre-Production
            steps:
              - step: *BuildStep
              - step: *TerraDeploy


    master:
      - parallel:
          fail-fast: true
          steps:
            - step: *SecretChecking
      - stage:
            name: Production Deployment
            deployment: Pre-Production
            steps:
              - step: *BuildStep
              - step: *TerraDeploy

            
