services:
  buyers:
    path: services/buyers
    config: ${env:config}
  bids:
    path: services/bids
    config: ${env:config}
  subdomain:
    path: services/subdomain
    config: ${env:config}
  address-management:
    path: services/address-management
    config: ${env:config}
  cart-management:
    path: services/cart-management
    config: ${env:config}
  buyer-wishlist:
    path: services/buyer-wishlist
    config: ${env:config}
  payments:
    path: services/payments
    config: ${env:config}
  order-management:
    path: services/order-management
    config: ${env:config}
  admin-management:
    path: services/admin-management
    config: ${env:config}
  lot-bid-history:
    path: services/lot-bid-history
    config: ${env:config}
  admin-buyer-management:
    path: services/admin-buyer-management
    config: ${env:config}
  seller-bidder-management:
    path: services/seller-bidder-management
    config: ${env:config}
  site-banner:
    path: services/site-banner
    config: ${env:config}
  paypal: 
    path: services/paypal
    config: ${env:config}
  newsletter:
    path: services/newsletter
    config: ${env:config}
  access-logs:
    path: services/access-logs
    config: ${env:config}
  redis-delete:
    path: services/redis-delete
    config: ${env:config}
  in-person-auction:
    path: services/in-person-auctions
    config: ${env:config}

