services:
  users:
    path: services/users
    config: ${env:config}
  auctions:
    path: services/auctions
    config: ${env:config}
  buyers:
    path: services/buyers
    config: ${env:config}
  lambda-authorizer:
    path: services/lambda-authorizer
    config: ${env:config}
  bids:
    path: services/bids
    config: ${env:config}
  Subdomain:
    path: services/Subdomain
    config: ${env:config}
  address-management:
    path: services/address-management
    config: ${env:config}
  cart-management:
    path: services/cart-management
    config: ${env:config}

    