services:
  users:
    path: services/users
    config: ${env:config}
  auctions:
    path: services/auctions
    config: ${env:config}
  # buyers:
  #   path: services/buyers
  #   config: ${env:config}
  lambda-authorizer:
    path: services/lambda-authorizer
    config: ${env:config}
  bids:
    path: services/bids
    config: ${env:config}
  subdomain:
    path: services/subdomain
    config: ${env:config}
  address-management:
    path: services/address-management
    config: ${env:config}
  cart-management:
    path: services/cart-management
    config: ${env:config}
  cognito-auth:
    path: services/cognito-auth
    config: ${env:config}
  buyer-wishlist:
    path: services/buyer-wishlist
    config: ${env:config}
  payments:
    path: services/payments
    config: ${env:config}
  order-management:
    path: services/order-management
    config: ${env:config}

 
