service: load-test
frameworkVersion: '3'
useDotenv: true
deprecationNotificationMode: error
disabledDeprecations:
  - UNSUPPORTED_CLI_OPTIONS
  - CLI_OPTIONS_SCHEMA_V3
  - CONFIG_VALIDATION_MODE_DEFAULT_V3
  - 
provider:
  name: aws
  endpointType: REGIONAL
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  region: eu-west-2
  versionFunctions: false
  layers:  ${ssm:NODE_LIB_ARN}
  environment:
    BUYER_RECAPTCHA_URL: https://www.google.com/recaptcha/api/siteverify
    TABLE_NAME: ${opt:stage, self:provider.stage}-${self:service}
    BUYER_WISHLIST_TABLE_NAME: ${opt:stage, self:provider.stage}-buyer-wishlists
    COGNITO_USER_POOL_ID: ${ssm:SELLER_COGNITO_USERPOOL_ID}
    COGNITO_SELLER_CLIENT_ID: ${ssm:SELLER_COGNITO_CLIENT_ID}
    REGION: ${env:REGION}
    STAGE: ${opt:stage, self:provider.stage}
    DATABASE: ${ssm:DATABASE}
    MONGODB_NAME: ${opt:stage, self:provider.stage}
    MONGODB_COLLECTION_NAME: ${opt:stage, self:provider.stage}-users
    MONGO_CLIENT: ${self:custom.mongodbConnectionString}
    AUCTION_MONGODB_COLLECTION_NAME: ${opt:stage, self:provider.stage}-auctions
    COGNITO_USER_POOL: ${ssm:SELLER_COGNITO_USERPOOL_NAME}
    SELLERS_TABLE: ${opt:stage, self:provider.stage}-users
    SUMSUB_SECRET_KEY: ${ssm:SUMSUB_SECRET_KEY}
    SUMSUB_APP_TOKEN: ${ssm:SUMSUB_APP_TOKEN}
    CSV_FILE:  /tmp/Auctions.csv
    S3_BUCKET:  ${ssm:BUCKET_NAME}
    LOT_COLLECTION_NAME: ${opt:stage, self:provider.stage}-lots
    COUNTER_LOT: ${opt:stage, self:provider.stage}-counters
    REGISTER_AUCTION_COLLECTION: ${opt:stage, self:provider.stage}-register-auction
    SUB_DOMAIN_TABLE: ${opt:stage, self:provider.stage}-subdomain
    USERPOOLS_MONGO: ${opt:stage, self:provider.stage}-userpools
    DEFAULT_SUB_DOMAIN: ${ssm:DEFAULT_SUB_DOMAIN}
    BUYER_COGNITO_USERPOOL_ID: ${ssm:BUYER_COGNITO_USERPOOL_ID}
    BUYER_COLLECTION: ${opt:stage, self:provider.stage}-buyers


  http:
    cors: true
    authorizers:
      cognito-auth:
        identitySource: $request.header.Authorization
        issuerUrl: https://cognito-idp.${env:REGION}.amazonaws.com/${ssm:SELLER_COGNITO_USERPOOL_ID}
        audience: ${ssm:SELLER_COGNITO_CLIENT_ID}


  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - cognito-idp:*
            - ses:*
            - s3:*
            - lambda:*
            - mobiletargeting:*
          Resource: "*"
 
package:
  patterns:
    - '!./node_modules/**'
    - ./handlers/**
    - ./data/**
    - ./entities/**
    - ./utils/**
    - ./lib/**

custom:
  isProd: ${self:provider.stage} # Will be resolved at deploy time
  mongodbConnectionString: ${file(../env.yml):${self:provider.stage}.MONGODB_CONNECTION_STRING}
  packageExternal:
    external:
      - '../../lib'
      - '../../entities'
      
  customDomain:
    rest:
      domainName: ${ssm:DOMAIN_NAME}
      stage: ${opt:stage, self:provider.stage}
      basePath: v1/${self:service}
      certificateName: ${ssm:DOMAIN_CERTIFICATE}
      createRoute53Record: true
      securityPolicy: tls_1_2
      endpointType: REGIONAL
  serverlessIfElse:
    - If: '${param:offline, "false"} == true'
      Set:
        provider.environment.MONGO_CLIENT: ${env:MONGODB_CONNECTION_STRING}

                


functions: 
  registration:
    handler: handlers/register.handler
    runtime: python3.9
    layers:
      -  ${ssm:NODE_LIB_ARN}
      -  ${ssm:PYTHON_LIB_ARN}
    vpc:
      securityGroupIds:
        - ${ssm:SECURITY_GROUP_ID}
      subnetIds:
        - ${ssm:SUBNET_ID}
    events:
      - http:
          cors: true
          path: /register
          method: POST
          # authorizer:
          #   arn: ${ssm:SELLER_COGNITO_AUTH_ARN}

  auction-registration:
    handler: handlers/register_auction.handler
    runtime: python3.9
    layers:
      -  ${ssm:NODE_LIB_ARN}
      -  ${ssm:PYTHON_LIB_ARN}
    vpc:
      securityGroupIds:
        - ${ssm:SECURITY_GROUP_ID}
      subnetIds:
        - ${ssm:SUBNET_ID}
    events:
      - http:
          cors: true
          path: /register-auction
          method: POST

  
  
plugins:
  - serverless-offline
  - serverless-package-external
  - serverless-domain-manager
  - serverless-plugin-ifelse
