service: users-management
frameworkVersion: '3'
useDotenv: true
deprecationNotificationMode: error
disabledDeprecations:
  - UNSUPPORTED_CLI_OPTIONS
  - CLI_OPTIONS_SCHEMA_V3
  - CONFIG_VALIDATION_MODE_DEFAULT_V3
  - 
provider:
  name: aws
  endpointType: REGIONAL
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  region: eu-west-2
  versionFunctions: false
  layers: ${ssm:COMMON_LIB_ARN}
  environment:
    TABLE_NAME: ${opt:stage, self:provider.stage}-${self:service}
    COGNITO_USER_POOL_ID: { Ref: SellerUsers }
    COGNITO_SELLER_CLIENT_ID: { Ref: SellerUsersClient } 
    REGION: ${env:REGION}
    STAGE: ${opt:stage, self:provider.stage}
    MONGODB_NAME: ${opt:stage, self:provider.stage}
    MONGODB_COLLECTION_NAME: ${opt:stage, self:provider.stage}-users
    MONGO_CLIENT: ${self:custom.mongodbConnectionString}
    CUSTOMER_SESSION_TOKEN_SECRET: ${ssm:CUSTOMER_SESSION_TOKEN_SECRET}
    RECAPTCHA_KEY: ${ssm:RECAPTCHA_KEY}
    TEMPLATE_ARN_EMAIL_OTP: 
      Fn::Join:
        - ":"
        - - "arn"
          - "aws"
          - "mobiletargeting"
          - !Ref "AWS::Region"
          - !Ref "AWS::AccountId"
          - "templates/${self:provider.stage}-email-otp-template/EMAIL"
    TEMPLATE_ARN_WELCOME_EMAIL: 
       Fn::Join:
        - ":"
        - - "arn"
          - "aws"
          - "mobiletargeting"
          - !Ref "AWS::Region"
          - !Ref "AWS::AccountId"
          - "templates/${self:provider.stage}-welcome_email_template/EMAIL" 
    PASSWORD_SECRET_KEY: ${ssm:PASSWORD_SECRET_KEY}
    RECAPTCHA_URL: https://www.google.com/recaptcha/api/siteverify
    SELLERS_TABLE: ${opt:stage, self:provider.stage}-users
    SES_SENDER_EMAIL_ID: ${ssm:SENDER_EMAIL_ADDRESS}
    JWT_SECRET_KEY: ${ssm:PASSWORD_SECRET_KEY}
    DATABASE: ${opt:stage, self:provider.stage}
    BASE_URL_SELLER: ${ssm:SELLER_APPLICATION_URL}
    FORGOT_PASSWORD_EMAIL_TEMPLATE_SELLER: ${self:provider.stage}-forgot-password
      # Fn::Join:
      #   - ":"
      #   - - "arn"
      #     - "aws"SendTemplatedEmail
      #     - "mobiletargeting"
      #     - !Ref "AWS::Region"
      #     - !Ref "AWS::AccountId"
      #     - "templates/${self:provider.stage}-forgot-password"
      #     - EMAIL
    SUMSUB_SECRET_KEY: ${ssm:SUMSUB_SECRET_KEY}
    SUMSUB_APP_TOKEN: ${ssm:SUMSUB_APP_TOKEN}
    LEVEL_NAME:  basic-kyc-level
    SUMSUB_SECRET_KEY_WEBHOOK: ${ssm:SUMSUB_SECRET_KEY_WEBHOOK}
    SELLER_GOOGLE_PASSWORD: INDY@SELLER
    DASHBOARD_URL: ${ssm:SELLER_DASHBOARD_APPLICATION_URL}
    KYB_LEVEL_NAME: basic-kyb-level
    STRIPE_API_KEY: ${ssm:STRIPE_API_KEY}
    DEFAULT_USERPOOL_ID: ${ssm:BUYER_COGNITO_USERPOOL_ID}
    DEFAULT_SUB_DOMAIN: ${ssm:DEFAULT_SUB_DOMAIN}
    DEFAULT_CLIENT_ID: ${ssm:BUYER_COGNITO_CLIENT_ID}
    REDIS_CLUSTER_ENDPOINT: ${ssm:REDIS_CLUSTER_ENDPOINT}
    MAILCHIMP_API_KEY: ${ssm:MAILCHIMP_SECRET_KEY}
    MAILCHIMP_SECRET_KEY: ${ssm:MAILCHIMP_SECRET_KEY}  #ADDED THIS FOR MAILCHIMP API CALL
    ACCESS_LOG_COLLECTION: ${opt:stage, self:provider.stage}-access-logs

   
    
  http:
    cors: true
     
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - cognito-idp:*
            - ses:*
            - s3:*
            - lambda:*
            - mobiletargeting:*
            # - lambda:RemovePermission 
          Resource: "*"
 
package:
  patterns:
    - '!./node_modules/**'
    - ./handlers/**
    - ./data/**
    - ./entities/**
    - ./utils/**
    - ./lib/**

custom:
  mongodbConnectionString: ${file(../env.yml):${self:provider.stage}.MONGODB_CONNECTION_STRING}
  packageExternal:
    external:
      - '../../lib'
      - '../../entities'
      
  customDomain:
    rest:
      domainName: ${ssm:DOMAIN_NAME}
      stage: ${opt:stage, self:provider.stage}
      basePath: v1/${self:service}
      certificateName: ${ssm:DOMAIN_CERTIFICATE}
      createRoute53Record: true
      securityPolicy: tls_1_2
      endpointType: REGIONAL
  serverlessIfElse:
    - If: '${param:offline, "false"} == true'
      Set:
        provider.environment.MONGO_CLIENT: ${env:MONGODB_CONNECTION_STRING}
                
  
 


functions: 


  verify-recaptha:
    handler: handlers/verify_the_recaptcha.verifyReCaptcha
    layers:
      - ${ssm:COMMON_LIB_ARN}
    vpc:
      securityGroupIds:
        - ${ssm:SECURITY_GROUP_ID}
      subnetIds:
        - ${ssm:SUBNET_ID}
    events:
      - http:
          path: /verify-captcha
          method: post
          cors: true
  
  otp-validation:
    handler: handlers/otp_validation.otpValidation
    layers:
      - ${ssm:COMMON_LIB_ARN}
    vpc:
      securityGroupIds:
        - ${ssm:SECURITY_GROUP_ID}
      subnetIds:
        - ${ssm:SUBNET_ID}
    events:
      - http:
          path: /otp-validation
          method: post
          cors: true
  
  request-otp:
    handler: handlers/request-otp.generate_otp
    layers:
      - ${ssm:COMMON_LIB_ARN}
    vpc:
      securityGroupIds:
        - ${ssm:SECURITY_GROUP_ID}
      subnetIds:
        - ${ssm:SUBNET_ID}
    events:
      - http:
          path: /request-otp
          method: post
          cors: true
      
  send-reset-link:
    handler: handlers/send_reset_link.send_reset_link
    runtime: python3.9
    layers:
      - ${ssm:COMMON_LIB_ARN_PYTHON}
    vpc:
      securityGroupIds:
        - ${ssm:SECURITY_GROUP_ID}
      subnetIds:
        - ${ssm:SUBNET_ID}
    events:
      - http:
          cors: true
          path: /forgot_password
          method: post

  update-new-password:
    handler: handlers/reset_password.password_reset
    runtime: python3.9
    layers: 
      - ${ssm:COMMON_LIB_ARN_PYTHON}
    vpc:
          securityGroupIds:
            - ${ssm:SECURITY_GROUP_ID}
          subnetIds:
            - ${ssm:SUBNET_ID}
    events:
      - http:
          cors: true
          path: /reset_password
          method: post
  
  view-profile:
    handler: handlers/view_profile.view_customer
    runtime: python3.9
    layers:
      - ${ssm:COMMON_LIB_ARN_PYTHON}
    vpc:
      securityGroupIds:
        - ${ssm:SECURITY_GROUP_ID}
      subnetIds:
        - ${ssm:SUBNET_ID}
  
    events:
        - http:
            cors: true
            path: /{email}
            method: GET
            authorizer:
              type: COGNITO_USER_POOLS
              authorizerId: { Ref: MyApiGatewayAuthorizer }



  update-profile:
        handler: handlers/update_profile.updateUserInformation
        layers:
          - ${ssm:COMMON_LIB_ARN}
        vpc:
          securityGroupIds:
            - ${ssm:SECURITY_GROUP_ID}
          subnetIds:
            - ${ssm:SUBNET_ID}
        events:
          - http:
              cors: true
              path: /{email}
              method: PATCH
              authorizer:
              type: COGNITO_USER_POOLS
              authorizerId: { Ref: MyApiGatewayAuthorizer }

  generate_token:
    handler: handlers/generate.generate_token
    runtime: python3.9
    memorySize: 128
    layers:
      - ${ssm:COMMON_LIB_ARN_PYTHON}
    vpc:
      securityGroupIds:
        - ${ssm:SECURITY_GROUP_ID}
      subnetIds:
        - ${ssm:SUBNET_ID}
    events:
      - http:
          cors: true
          path: /generate
          method: get
          authorizer:
              type: COGNITO_USER_POOLS
              authorizerId: { Ref: MyApiGatewayAuthorizer }

  kyc_webhook:
    handler: handlers/kyc_webhook.kyc_webhook
    runtime: python3.9
    memorySize: 128
    layers:
      - ${ssm:COMMON_LIB_ARN_PYTHON}
    vpc:
      securityGroupIds:
        - ${ssm:SECURITY_GROUP_ID}
      subnetIds:
        - ${ssm:SUBNET_ID}
    events:
      - http:
          cors: true
          path: /kyc
          method: post


  update-password:
        handler: handlers/update_password.updatePassword
        layers:
          - ${ssm:COMMON_LIB_ARN}
        vpc:
          securityGroupIds:
            - ${ssm:SECURITY_GROUP_ID}
          subnetIds:
            - ${ssm:SUBNET_ID}
        events:
          - http:
              cors: true
              path: /password-update/{email}
              method: PATCH
              authorizer:
              type: COGNITO_USER_POOLS
              authorizerId: { Ref: MyApiGatewayAuthorizer }

  update-plans:
        handler: handlers/update_plan.updatePlan
        layers:
          - ${ssm:COMMON_LIB_ARN}
        vpc:
          securityGroupIds:
            - ${ssm:SECURITY_GROUP_ID}
          subnetIds:
            - ${ssm:SUBNET_ID}
        events:
          - http:
              cors: true
              path: /update-plan/{email}
              method: PATCH
              authorizer:
              type: COGNITO_USER_POOLS
              authorizerId: { Ref: MyApiGatewayAuthorizer }
  
  kyb_generate_token:
    handler: handlers/kyb_generate.generate_token
    runtime: python3.9
    memorySize: 128
    layers:
      - ${ssm:COMMON_LIB_ARN_PYTHON}
    vpc:
      securityGroupIds:
        - ${ssm:SECURITY_GROUP_ID}
      subnetIds:
        - ${ssm:SUBNET_ID}
    events:
      - http:
          cors: true
          path: /kyb-generate
          method: get
          authorizer:
              type: COGNITO_USER_POOLS
              authorizerId: { Ref: MyApiGatewayAuthorizer }

  split_payment:
    handler: handlers/split_payment.splitPayment
    memorySize: 128
    layers:
      - ${ssm:COMMON_LIB_ARN_PYTHON}
    vpc:
      securityGroupIds:
        - ${ssm:SECURITY_GROUP_ID}
      subnetIds:
        - ${ssm:SUBNET_ID}
    events:
      - http:
          cors: true
          path: /payment-intent
          method: get
          authorizer:
              type: COGNITO_USER_POOLS
              authorizerId: { Ref: MyApiGatewayAuthorizer }
    
  seller_sub_domain:
    handler: handlers/seller_domain.create_subdomain
    runtime: python3.9
    memorySize: 128
    layers:
      - ${ssm:COMMON_LIB_ARN_PYTHON}
    vpc:
      securityGroupIds:
        - ${ssm:SECURITY_GROUP_ID}
      subnetIds:
        - ${ssm:SUBNET_ID}
    events:
      - http:
          cors: true
          path: /seller-sub-domain
          method: post
          authorizer:
              type: COGNITO_USER_POOLS
              authorizerId: { Ref: MyApiGatewayAuthorizer }

  disconnect_account:
    handler: handlers/stripe_disconnect.disconnect_account
    runtime: python3.9
    layers:
      - ${ssm:COMMON_LIB_ARN_PYTHON}
    vpc:
      securityGroupIds:
        - ${ssm:SECURITY_GROUP_ID}
      subnetIds:
        - ${ssm:SUBNET_ID}
    events:
      - http:
          cors: true
          path: /stripe
          method: patch
          authorizer:
              type: COGNITO_USER_POOLS
              authorizerId: { Ref: MyApiGatewayAuthorizer }

  stripe-connect:
    handler: handlers/create.create
    runtime: python3.9
    layers:
      - ${ssm:COMMON_LIB_ARN_PYTHON}
    vpc:
      securityGroupIds:
        - ${ssm:SECURITY_GROUP_ID}
      subnetIds:
        - ${ssm:SUBNET_ID}
    events:
        - http:
            cors: true
            path: /stripe
            method: GET
            authorizer:
              type: COGNITO_USER_POOLS
              authorizerId: { Ref: MyApiGatewayAuthorizer }

  stripe-webhook:
      handler: handlers/stripe_webhook.create
      runtime: python3.9
      layers:
        - ${ssm:COMMON_LIB_ARN_PYTHON}
      vpc:
        securityGroupIds:
          - ${ssm:SECURITY_GROUP_ID}
        subnetIds:
          - ${ssm:SUBNET_ID}
    
      events:
          - http:
              cors: true
              path: /stripe_webhook_trigger
              method: any
              # authorizer:
              #   arn: ${ssm:SELLER_COGNITO_AUTH_ARN}

  save-logs:
      handler: handlers/login_log.handler
      layers:
        - ${ssm:COMMON_LIB_ARN}
      vpc:
        securityGroupIds:
          - ${ssm:SECURITY_GROUP_ID}
        subnetIds:
          - ${ssm:SUBNET_ID}
    
      events:
          - http:
              cors: true
              path: /save-log
              method: POST
              authorizer:
                arn: ${ssm:SELLER_COGNITO_AUTH_ARN}

plugins:
  - serverless-offline
  - serverless-package-external
  - serverless-domain-manager
  - serverless-plugin-ifelse



