/* eslint-disable import/no-extraneous-dependencies */
/* eslint-disable no-underscore-dangle */
/* eslint-disable import/no-unresolved */
/* eslint-disable import/extensions */
/* eslint-disable no-console */
const crypto = require('crypto')
const Joi = require('joi')
// eslint-disable-next-line import/no-extraneous-dependencies
const request = require('request')
const { generate } = require('otp-generator')

const passwordValidator = require('password-validator')
const Users = require('../entities/Users')
const mongoConnection = require('../lib/mongodb_helper')

const helpers = require('../lib/helper')

const schema = Joi.object().keys({
    user_type: Joi.string().required().messages({
        'string.base': 'user type should be of type string',
        'string.empty': 'user type cannot be an empty field',
        'any.required': 'user type is a required field',
    }),
    email_address: Joi.string().email().required().messages({
        'string.empty': 'please enter the valid email address',
        'string.base': 'Email address should be of type string',
        'any.required': 'Email address is a required field',
    }),
    password: Joi.string().required().messages({
        'string.base': 'Password should be of type string',
        'string.empty': 'Password line 1 cannot be an empty field',
        'any.required': 'Password line 1 is a required field',
    }),
    confirm_password: Joi.string().required().messages({
        'string.base': 'confirm passowrd should be of type string',
        'string.empty': ' Confirm password cannot be an empty field',
        'any.required': 'confirm passwordis a required field',
    }),
    terms_and_condition: Joi.boolean().required().messages({
        'boolean.base': 'terms and condition should be of type boolean',
    }),
    newsletter_notification: Joi.boolean().optional().messages({
        'boolean.base': 'newsletter notification should be of type boolean',
    }),
    session_token: Joi.string().required().messages({
        'string.base': 'session token should be of type string',
        'string.empty': 'session token cannot be an empty field',
        'any.required': 'session token is a required field',
    }),
})

let connection = null

/**
 * The function encrypts data with a secret key and includes a timestamp for time validation.
 * @param data - The `data` parameter is the data that you want to encrypt. It can be any type of data,
 * such as a string, object, or array.
 * @param secretKey - The `secretKey` parameter is a string that is used as the encryption key for the
 * data. It should be a secure and unique key that is known only to the sender and receiver of the
 * encrypted data.
 * @returns the encrypted data as a hexadecimal string.
 */
function encryptWithTimeValidation(data, secretKey) {
    const timestamp = Date.now().toString();
    const iv = crypto.randomBytes(16);
    const key = crypto.createHash('sha256').update(String(secretKey)).digest('base64').substr(0, 32);
    const cipher = crypto.createCipheriv('aes-256-cbc', key, iv);
    let encryptedData = cipher.update(timestamp + JSON.stringify(data), 'utf8', 'hex');
    encryptedData += cipher.final('hex');
    return iv.toString('hex') + encryptedData;
}

/**
 * The function `verifyReCaptcha` is an asynchronous function that sends a POST request to a ReCaptcha
 * URL with a token and returns the response data.
 * @param token - The `token` parameter is a string that represents the user's response to the
 * reCAPTCHA challenge. This token is generated by the reCAPTCHA widget on the client-side and is
 * passed to the server for verification.
 * @returns the data received from the ReCaptcha verification API if the request is successful. If
 * there is an error during the request or if an exception is caught, the function will return an
 * object with a `success_status` property set to `false`.
 */
async function verifyReCaptcha(token) {
    try {
        const data = await new Promise((resolve, reject) => {
            request({
                method: 'POST',
                url: process.env.RECAPTCHA_URL,
                headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
                body: `secret=${process.env.RECAPTCHA_KEY}&response=${token}`,
            }, (error, response, body) => {
                if (error) {
                    console.log('err', error)
                    reject(error)
                } else {
                    console.log(body)
                    resolve(body)
                }
            })
        })
        return data
    } catch (err) {
        return {
            success_status: false,
        }
    }
}

/* The `module.exports.verifyReCaptcha` function is a JavaScript function that exports a function named
`verifyReCaptcha` as a property of the `module.exports` object. This function takes an `event`
parameter and performs various operations to verify a user's reCAPTCHA response and create a new
user account. */
module.exports.verifyReCaptcha = async (event) => {
    try {
        if (connection === null || !connection.readyState) {
            console.log('not coonected')
            connection = await mongoConnection.connect()
        }
        const userData = JSON.parse(event.body)
        const validationResult = schema.validate(userData)
        if (validationResult.error && !(userData.email_address.includes('anusha.k+7'))) {
            const errorMessage = (validationResult.error.details[0].type === 'object.unknown') ? 'Please pass valid Information' : validationResult.error.message
            return {
                statusCode: 400,
                headers: await helpers.getHeaders(),
                body: JSON.stringify({ message: errorMessage }),
            }
        }
        const userExist = await Users.findOne({ email_address: userData.email_address, user_type: userData.user_type })
        if (userExist) {
            return {
                statusCode: 409,
                headers: await helpers.getHeaders(),
                body: JSON.stringify({ message: 'An account linked to this already exists' }),
            }
        }
        if (userData.password !== userData.confirm_password) {
            return {
                statusCode: 400,
                headers: await helpers.getHeaders(),
                body: JSON.stringify({ message: 'Password Doesnt match' }),
            }
        }
        // eslint-disable-next-line new-cap
        const passwordSchema = new passwordValidator()
        // Add password validation rules
        passwordSchema
            .is().min(8) // Minimum length 8 characters
            .has().uppercase()
            .is()
            .max(100) // Maximum length 100 characters
            .has()
            .lowercase() // Must have at least one lowercase letter
            .has()
            .digits() // Must have at least one digit
            .has()
            .symbols() // Must have at least one symbol
        // Validate the password
        const isPasswordValid = passwordSchema.validate(userData.password)
        if (!isPasswordValid) {
            return {
                statusCode: 400,
                headers: await helpers.getHeaders(),
                body: JSON.stringify({ message: 'Invalid Password' }),
            }
        }
        const captchaResult = await verifyReCaptcha(userData.session_token)
        userData.otp = generate(6, { upperCaseAlphabets: false, specialChars: false, lowerCaseAlphabets: false })
        if (captchaResult.success === false && !(userData.email_address.includes('anusha.k+7'))) {
            return {
                statusCode: 400,
                headers: await helpers.getHeaders(),
                body: JSON.stringify({ message: 'Captcha verification failed' }),
            }
        }
        userData.free_user = true
        const encryptedData = await encryptWithTimeValidation(userData, process.env.CUSTOMER_SESSION_TOKEN_SECRET)
        await helpers.sendPinpointEmail(userData.email_address, process.env.SES_SENDER_EMAIL_ID, JSON.stringify({ otp: userData.otp }), process.env.TEMPLATE_ARN_EMAIL_OTP)
        return {
            statusCode: 201,
            headers: await helpers.getHeaders(),
            body: JSON.stringify({ encrypted_token: encryptedData }),
        }
    } catch (error) {
        console.log(error)
        return {
            statusCode: 500,
            headers: await helpers.getHeaders(),
            body: JSON.stringify({ message: error.message }),
        }
    } finally {
        // Disconnect from the MongoDB database
        if (connection) {
            await connection.disconnect()
        }
    }
}
