module.exports = {
    secret: process.env.secret || 'PetsRWisecwm2weEqyG3Y3CXUi3ororim030Qw0o',
    refreshTokenSecret: process.env.refreshTokenSecret || 'LdlyhvYRVNkD1wlpIfkseyJ1c2VyRW1haWxJZCI6ImFkbWluQHBldHNyd2lzZS5j',
    port: 5000,
    tokenLife: '2h',
    refreshTokenLife: 2592000,
    region: process.env.region || 'ap-south-1',
    endpoint: 'http://localhost:3000',
    stage: process.env.stage || 'dev',
    verifyPhoneOtpSecret: 'APA91bGPlN0ph4ghLm6n16FM23ONZYsbTATSN9lqZkcDlHVv0YAsMMBOHyiRYBFwNwq3YQDHOsn72z',
    FCMKEY: 'AAAAQl0eWgA:APA91bGPlN0ph4ghLm6n16FM23ONZYsbTATSN9lqZkcDlHVv0YAsMMBOHyiRYBFwNwq3YQDHOsn72zRFevi6po9Mepdxdwusc7x_aYMtUxe5yDhVuyhx01q7MunsHM1kAKe1ORbjYjUK',
    // mongoDBConnectionString: 'mongodb://master_admin_user:petsRWise!7EDGE@52.208.197.40:27017/petsrwise_development?authSource=admin',
    petImageUrl: 'https://petsrwise-development.s3.sa-east-1.amazonaws.com',
    bucketRegion: 'us-east-1',
    accessKeyId: process.env.accessKeyId || 'AKIA5UPVYNV6MOILJJHO',
    secretAccessKey: process.env.secretAccessKey || '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',
    bucket: 'prw-email-templates',
    imageBucket: 'petsrwise-development',
    paymentJwtSecret: 'APA91bGPlN0ph4ghLm6n16FM23ONZYsbTATSN9lqZkcDlHVv0YAsMMBOHyiRYBFwNwq3YQDHOsn72z',
    paymentJwtTokenExpiresIn: '900s',
    // APIEndpoint: 'https://securepayments.petsrwise.com/payments/membership/cancel_membership/',
    APIEndpoint: 'https://staging-payments.petsrwise.com/payments/membership/cancel_membership/',
    // refundApi: 'https://securepayments.petsrwise.com/payments/refund/',
    refundApi: 'https://staging-payments.petsrwise.com/payments/refund/',
    // verifyEmailUrl: 'https://api.petsrwise.com/api/v1/user/verify_email',
    verifyEmailUrl: 'https://staging-apis.petsrwise.com/api/v1/user/verify_email',
    forgotPasswordUrl: 'https://api.petsrwise.com/api/v1/user',
    forgotPasswordSecret: '5fd300a7695fd305fd300a76924529dfcf5ac7b0a76924529dfcf5ac7b24529dfcf5a5fd300a76924529dfcf5ac7bc7b',
    // membershipPaymentUrl: 'https://securepayments.petsrwise.com/payments/membership/order/',
    membershipPaymentUrl: 'https://staging-payments.petsrwise.com/payments/membership/order/',
    // orderPaymentUrl: 'https://securepayments.petsrwise.com/payments/order/',
    orderPaymentUrl: 'https://staging-payments.petsrwise.com/payments/order/',
    websiteURL: 'https://www.petsrwise.com/',
    verifyEmailSecret: '5fd300a7695fd305fd300a76924529dfcf5ac7b0a76924529dfcf5ac7b24529dfcf5a5fd300a76924529dfcf5ac7bc7b',
    // "verifyEmailUrl":"https://api.petsrwise.com/api/v1/user/verify_email",
    // mongoDBConnectionString: 'mongodb://localhost:27017/petsrwise-development',
    mongoDBConnectionString: 'mongodb://devAdmin:petsrwise@3.217.180.16:3000:27017/petsrwise-develop?authSource=admin',
    // Partner Image uploading credentials
    partnerProfileImageS3Bucket: 'petsrwise-development-v1',
    partnerProfileImageS3BucketRegion: 'us-east-1',
    partnerProfileImageS3BucketFolderName: 'dynamic-assets/',
    partnerProfileImageS3BucketBaseUrl: 'https://petsrwise-development-v1.s3.amazonaws.com/',
    googleCalendarAuthCredentials: {
        installed: {
            client_id: '285030111744-uod4vrsesu8ihsl3dg4ni61scnpr2b2h.apps.googleusercontent.com',
            project_id: 'pets-r-wise',
            auth_uri: 'https://accounts.google.com/o/oauth2/auth',
            token_uri: 'https://oauth2.googleapis.com/token',
            auth_provider_x509_cert_url: 'https://www.googleapis.com/oauth2/v1/certs',
            redirect_uris: [
                'urn:ietf:wg:oauth:2.0:oob',
                'http://localhost',
            ],
        },
    },
}
