service: bids
frameworkVersion: '3'
useDotenv: true
deprecationNotificationMode: error
disabledDeprecations:
  - UNSUPPORTED_CLI_OPTIONS
  - CLI_OPTIONS_SCHEMA_V3
  - CONFIG_VALIDATION_MODE_DEFAULT_V3
  - 
provider:
  name: aws
  endpointType: REGIONAL
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  region: eu-west-2
  versionFunctions: false
  layers: ${ssm:COMMON_LIB_ARN}
  environment:
    TABLE_NAME: ${opt:stage, self:provider.stage}-${self:service}
    COGNITO_USER_POOL_ID: ${ssm:SELLER_COGNITO_USERPOOL_ID}
    COGNITO_SELLER_CLIENT_ID: ${ssm:SELLER_COGNITO_CLIENT_ID}
    REGION: ${env:REGION}
    STAGE: ${opt:stage, self:provider.stage}
    DATABASE: ${ssm:DATABASE}
    MONGODB_NAME: ${opt:stage, self:provider.stage}
    MONGODB_COLLECTION_NAME: ${opt:stage, self:provider.stage}-users
    MONGO_CLIENT: ${self:custom.mongodbConnectionString}
    AUCTION_MONGODB_COLLECTION_NAME: ${opt:stage, self:provider.stage}-auctions
    COGNITO_USER_POOL: ${ssm:SELLER_COGNITO_USERPOOL_NAME}
    SELLERS_TABLE: ${opt:stage, self:provider.stage}-users
    SUMSUB_SECRET_KEY: ${ssm:SUMSUB_SECRET_KEY}
    SUMSUB_APP_TOKEN: ${ssm:SUMSUB_APP_TOKEN}
    CSV_FILE:  /tmp/Auctions.csv
    S3_BUCKET:  ${ssm:BUCKET_NAME}
    LOT_COLLECTION_NAME: ${opt:stage, self:provider.stage}-lots
    COUNTER_LOT: ${opt:stage, self:provider.stage}-counters
    REGISTER_AUCTION_COLLECTION: ${opt:stage, self:provider.stage}-register-auction
    SUB_DOMAIN_TABLE: ${opt:stage, self:provider.stage}-subdomain
    USERPOOLS_MONGO: ${opt:stage, self:provider.stage}-userpools
    MAILCHIMP_SECRET_KEY: ${ssm:MAILCHIMP_SECRET_KEY}
    #KMS_KEY_ID: ${ssm:KMS_KEY_ID}
    REDIS_CLUSTER_ENDPOINT: ${ssm:REDIS_CLUSTER_ENDPOINT}
    BUYER_EMAIL_OTP_TEMPLATE: 
      Fn::Join:
        - ":"
        - - "arn"
          - "aws"
          - "mobiletargeting"
          - !Ref "AWS::Region"
          - !Ref "AWS::AccountId"
          - "templates/${self:provider.stage}-buyer_email_otp/EMAIL"
          
    ENCRYPTION_SECRET_KEY: Indy@auction@789
    BUYER_COLLECTION: ${opt:stage, self:provider.stage}-buyers
    RECAPTCHA_KEY: ${ssm:RECAPTCHA_KEY}
    RECAPTCHA_URL: https://www.google.com/recaptcha/api/siteverify
    CUSTOMER_SESSION_TOKEN_SECRET: ${ssm:CUSTOMER_SESSION_TOKEN_SECRET}
    SES_SENDER_EMAIL_ID: ${ssm:SENDER_EMAIL_ADDRESS}
    DEFAULT_SUB_DOMAIN: ${ssm:DEFAULT_SUB_DOMAIN}    
    JWT_SECRET_KEY: ${ssm:PASSWORD_SECRET_KEY}
    TEMPLATE_ARN_EMAIL_RESET_PASSWORD:  
      Fn::Join:
        - ":"
        - - "arn"
          - "aws"
          - "mobiletargeting"
          - !Ref "AWS::Region"
          - !Ref "AWS::AccountId"
          - "templates/${self:provider.stage}-buyer_reset_password/EMAIL"
         
   
    BASE_URL_BUYER: ${ssm:BASE_URL_BUYER}
    DEFAULT_USERPOOL_ID: ${ssm:BUYER_COGNITO_USERPOOL_ID}
    
  http:
    cors: true
     

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - cognito-idp:*
            - ses:*
            - s3:*
            - lambda:*
            - mobiletargeting:*
            - dynamodb:*
            - execute-api:*
          Resource: "*"
 
package:
  patterns:
    - '!./node_modules/**'
    - ./handlers/**
    - ./data/**
    - ./entities/**
    - ./utils/**
    - ./lib/**

custom:
  isProd: ${self:provider.stage} # Will be resolved at deploy time
  mongodbConnectionString: ${file(../env.yml):${self:provider.stage}.MONGODB_CONNECTION_STRING}
  packageExternal:
    external:
      - '../../lib'
      - '../../entities'
      
  customDomain:
    rest:
      domainName: ${ssm:DOMAIN_NAME}
      stage: ${opt:stage, self:provider.stage}
      basePath: v1/${self:service}
      certificateName: ${ssm:DOMAIN_CERTIFICATE}
      createRoute53Record: true
      securityPolicy: tls_1_2
      endpointType: REGIONAL

  serverlessIfElse:
    - If: '${param:offline, "false"} == true'
      Set:
        provider.environment.MONGO_CLIENT: ${env:MONGODB_CONNECTION_STRING}

functions: 
  list:
    handler: handlers/list.list_bidders
    runtime: python3.9
    layers:
      - ${ssm:COMMON_LIB_ARN_PYTHON}
    vpc:
      securityGroupIds:
        - ${ssm:SECURITY_GROUP_ID}
      subnetIds:
        - ${ssm:SUBNET_ID}
    events:
      - http:
          cors: true
          path: /
          method: get
          authorizer:
              arn: ${ssm:SELLER_COGNITO_AUTH_ARN}
  view:
    handler: handlers/view.view_bidder
    runtime: python3.9
    layers:
      - ${ssm:COMMON_LIB_ARN_PYTHON}
    vpc:
      securityGroupIds:
        - ${ssm:SECURITY_GROUP_ID}
      subnetIds:
        - ${ssm:SUBNET_ID}
    events:
      - http:
          cors: true
          path: /{id}
          method: get
          authorizer:
              arn: ${ssm:SELLER_COGNITO_AUTH_ARN}
  admin-view:
    handler: handlers/admin_view.view_bidder
    runtime: python3.9
    layers:
      - ${ssm:COMMON_LIB_ARN_PYTHON}
    vpc:
      securityGroupIds:
        - ${ssm:SECURITY_GROUP_ID}
      subnetIds:
        - ${ssm:SUBNET_ID}
    events:
      - http:
          cors: true
          path: /admin/{id}
          method: get
          authorizer:
              arn: ${ssm:ADMIN_COGNITO_AUTH_ARN}

  add-to-group:
    handler: handlers/update.update_user
    runtime: python3.9
    layers: 
      - ${ssm:COMMON_LIB_ARN_PYTHON}
    vpc:
        securityGroupIds:
          - ${ssm:SECURITY_GROUP_ID}
        subnetIds:
          - ${ssm:SUBNET_ID}
    events:
      - http:
          cors: true
          path: /update
          method: patch
          authorizer: ${ssm:BUYER_COGNITO_AUTH_ARN}        #arn:aws:lambda:${aws:region}:${aws:accountId}:function:lambda-authorizer-${self:provider.stage}-lambda-authorizer


resources:
  Conditions:
    IsProd:
      Fn::Equals:
        - ${self:custom.isProd}
        - prod
  Resources:
    GatewayResponseDefault4XX:
       Type: 'AWS::ApiGateway::GatewayResponse'
       Properties:
         ResponseParameters:
           gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
           gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
         ResponseType: DEFAULT_4XX
         RestApiId:
           Ref: 'ApiGatewayRestApi'
    WebAclAssociation:
      Condition: IsProd
      Type: AWS::WAFv2::WebACLAssociation
      Properties:
        ResourceArn:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}::/restapis/${ApiGatewayRestApi}/stages/${self:provider.stage}
        WebACLArn: ${ssm:SECURE_API_WEB_ACL_ARN}
    # BuyerEmailOtp:
    #   Type: AWS::Pinpoint::EmailTemplate
    #   Properties: 
    #     HtmlPart: ${file(./templates/buyer_email_otp.html)}
    #     Subject: Indy.auction - OTP Verification for Your Account
    #     TemplateName: ${self:provider.stage}-buyer_email_otp

    # BuyerResetPassword:
    #   Type: AWS::Pinpoint::EmailTemplate
    #   Properties: 
    #     HtmlPart: ${file(./templates/buyer_reset_password.html)}
    #     Subject: Indy.auction- Reset your password
    #     TemplateName: ${self:provider.stage}-buyer_reset_password

plugins:
  - serverless-offline
  - serverless-package-external
  - serverless-domain-manager
  - serverless-plugin-ifelse