service: cognito-buyer-resources
frameworkVersion: "3"
useDotenv: true


provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  region: eu-west-2
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - states:*
            - dynamodb:*
            - lambda:*
            - cognito-idp:*
            - s3:*
            - execute-api:*
            - ses:*
            - mobiletargeting:*
          Resource: "*"
          
  environment:
    TABLE_NAME: ${opt:stage, self:provider.stage}-${self:service}
    OTP_TABLE_NAME: ${opt:stage, self:provider.stage}-merchant-otp
    STORES_TABLE_NAME: ${opt:stage, self:provider.stage}-stores
    EMPLOYEES_TABLE_NAME: ${opt:stage, self:provider.stage}-employees
    COGNITO_USER_POOL_ID: ${env:COGNITO_USER_POOL_ID}
    COGNITO_CLIENT_ID: ${env:COGNITO_CLIENT_ID}
    REGION: ${env:REGION}
    AWS_ACCOUNT_ID: ${env:AWS_ACCOUNT_ID}
    STAGE: ${opt:stage, self:provider.stage}
    S3_BUCKET_NAME: ${env:S3_BUCKET_NAME}
    MERCHANT_CSV_FILES_FOLDER_NAME: csv-files/merchant-users
    TEMP_FOLDER: '/tmp/'
    MONGODB_CONNECTION_STRING: ${env:MONGODB_CONNECTION_STRING}
    PASSWORD_SECRET_KEY: ${env:PASSWORD_SECRET_KEY}
    DEBUG: ${env:DEBUG}
    DEVELOPER_MODE: ${env:DEVELOPER_MODE}
    MESSAGE_TEMPLATE_SID: ${env:MESSAGE_TEMPLATE_SID}
    MESSAGE_SERVICE_SID: ${env:MESSAGE_SERVICE_SID}
    TWILIO_PHONE_NUMBER: ${env:TWILIO_PHONE_NUMBER}
    LOGIN_SMS_TEMPLATE: ${env:LOGIN_SMS_TEMPLATE}
    FACEBOOK_APP_ID: ${env:FACEBOOK_APP_ID}
    FACEBOOK_APP_SECRET: ${env:FACEBOOK_APP_SECRET}

package:
  patterns:
    - ./handlers/**
    - ./data/**
    - ./utils/**
    - ./lib/**

resources:
  Resources:
    BuyerUsers:
      Type: "AWS::Cognito::UserPool"
      Properties:
        UserPoolName: ${self:provider.stage}-indyauction-buyers
        Policies:
          PasswordPolicy:
            MinimumLength: 6
            RequireUppercase: true
            RequireLowercase: true
            RequireNumbers: true
            RequireSymbols: false
            TemporaryPasswordValidityDays: 7
        DeletionProtection: ACTIVE
        Schema:
          - Name: sub
            AttributeDataType: String
            DeveloperOnlyAttribute: false
            Mutable: false
            Required: true
            StringAttributeConstraints:
              MinLength: "1"
              MaxLength: "2048"
          - Name: name
            AttributeDataType: String
            DeveloperOnlyAttribute: false
            Mutable: true
            Required: false
            StringAttributeConstraints:
              MinLength: "0"
              MaxLength: "2048"
          - Name: given_name
            AttributeDataType: String
            DeveloperOnlyAttribute: false
            Mutable: true
            Required: false
            StringAttributeConstraints:
              MinLength: "0"
              MaxLength: "2048"
          - Name: family_name
            AttributeDataType: String
            DeveloperOnlyAttribute: false
            Mutable: true
            Required: false
            StringAttributeConstraints:
              MinLength: "0"
              MaxLength: "2048"
          - Name: middle_name
            AttributeDataType: String
            DeveloperOnlyAttribute: false
            Mutable: true
            Required: false
            StringAttributeConstraints:
              MinLength: "0"
              MaxLength: "2048"
          - Name: nickname
            AttributeDataType: String
            DeveloperOnlyAttribute: false
            Mutable: true
            Required: false
            StringAttributeConstraints:
              MinLength: "0"
              MaxLength: "2048"
          - Name: preferred_username
            AttributeDataType: String
            DeveloperOnlyAttribute: false
            Mutable: true
            Required: false
            StringAttributeConstraints:
              MinLength: "0"
              MaxLength: "2048"
          - Name: profile
            AttributeDataType: String
            DeveloperOnlyAttribute: false
            Mutable: true
            Required: false
            StringAttributeConstraints:
              MinLength: "0"
              MaxLength: "2048"
          - Name: picture
            AttributeDataType: String
            DeveloperOnlyAttribute: false
            Mutable: true
            Required: false
            StringAttributeConstraints:
              MinLength: "0"
              MaxLength: "2048"
          - Name: website
            AttributeDataType: String
            DeveloperOnlyAttribute: false
            Mutable: true
            Required: false
            StringAttributeConstraints:
              MinLength: "0"
              MaxLength: "2048"
          - Name: email
            AttributeDataType: String
            DeveloperOnlyAttribute: false
            Mutable: true
            Required: true
            StringAttributeConstraints:
              MinLength: "0"
              MaxLength: "2048"
          - Name: email_verified
            AttributeDataType: Boolean
            DeveloperOnlyAttribute: false
            Mutable: true
            Required: false
          - Name: gender
            AttributeDataType: String
            DeveloperOnlyAttribute: false
            Mutable: true
            Required: false
            StringAttributeConstraints:
              MinLength: "0"
              MaxLength: "2048"
          - Name: birthdate
            AttributeDataType: String
            DeveloperOnlyAttribute: false
            Mutable: true
            Required: false
            StringAttributeConstraints:
              MinLength: "10"
              MaxLength: "10"
          - Name: zoneinfo
            AttributeDataType: String
            DeveloperOnlyAttribute: false
            Mutable: true
            Required: false
            StringAttributeConstraints:
              MinLength: "0"
              MaxLength: "2048"
          - Name: locale
            AttributeDataType: String
            DeveloperOnlyAttribute: false
            Mutable: true
            Required: false
            StringAttributeConstraints:
              MinLength: "0"
              MaxLength: "2048"
          - Name: phone_number
            AttributeDataType: String
            DeveloperOnlyAttribute: false
            Mutable: true
            Required: false
            StringAttributeConstraints:
              MinLength: "0"
              MaxLength: "2048"
          - Name: phone_number_verified
            AttributeDataType: Boolean
            DeveloperOnlyAttribute: false
            Mutable: true
            Required: false
          - Name: address
            AttributeDataType: String
            DeveloperOnlyAttribute: false
            Mutable: true
            Required: false
            StringAttributeConstraints:
              MinLength: "0"
              MaxLength: "2048"
          - Name: updated_at
            AttributeDataType: Number
            DeveloperOnlyAttribute: false
            Mutable: true
            Required: false
            NumberAttributeConstraints:
              MinValue: "0"
          - Name: identities
            AttributeDataType: String
            DeveloperOnlyAttribute: false
            Mutable: true
            Required: false
            StringAttributeConstraints:
              MaxLength: "2048"
          
        AliasAttributes:
          - preferred_username
        # AliasAttributes:
        #   - email
        # UsernameAttributes: 
        #   - email
        VerificationMessageTemplate:
          DefaultEmailOption: CONFIRM_WITH_CODE
        UserAttributeUpdateSettings:
          AttributesRequireVerificationBeforeUpdate: []
        MfaConfiguration: "OFF"
        # EnabledMfas:
        #   - SOFTWARE_TOKEN_MFA
        EmailConfiguration:
          EmailSendingAccount: COGNITO_DEFAULT
        UsernameConfiguration:
          CaseSensitive: true
        AccountRecoverySetting:
          RecoveryMechanisms:
            - Priority: 1
              Name: admin_only
    
    
    
    GoogleAuth:
      Type: "AWS::Cognito::UserPoolIdentityProvider"
      Properties:
        AttributeMapping:
          preferred_username: "email"
          username: "email"
          email: "sub"
        ProviderName: Google
        ProviderType: Google
        ProviderDetails:
          client_id: ${env:GOOGLE_CLIENT_ID}
          client_secret: ${env:GOOGLE_CLIENT_SECRET}
          authorize_scopes: "email openid profile"
        UserPoolId: { Ref: BuyerUsers }
          
    
    FacebookAuth:
      Type: "AWS::Cognito::UserPoolIdentityProvider"
      Properties:
        AttributeMapping:
          preferred_username: "email"
          username: "id"
          email: "email"
        ProviderName: Facebook
        ProviderType: Facebook
        ProviderDetails:
          client_id: ${env:FACEBOOK_CLIENT_ID}
          client_secret: ${env:FACEBOOK_CLIENT_SECRET}
          authorize_scopes: "email openid profile"
        UserPoolId: { Ref: BuyerUsers }
    
    
    
    BuyerUsersDomain:
      Type: "AWS::Cognito::UserPoolDomain"
      Properties:
        Domain: buyers-indyauction-${self:provider.stage}
        UserPoolId: { Ref: BuyerUsers }

    BuyerUsersClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        AccessTokenValidity: 60
        AllowedOAuthFlowsUserPoolClient: true
        AuthSessionValidity: 10
        ClientName: seller
        UserPoolId: { Ref: BuyerUsers }
        EnablePropagateAdditionalUserContextData: false
        EnableTokenRevocation: true
        ExplicitAuthFlows:
          - ALLOW_CUSTOM_AUTH
          - ALLOW_REFRESH_TOKEN_AUTH
          - ALLOW_USER_SRP_AUTH
          - ALLOW_ADMIN_USER_PASSWORD_AUTH
        SupportedIdentityProviders:
          - "COGNITO"
          - "Google"
          - "Facebook"
        AllowedOAuthFlows:
          - implicit
          - code
        AllowedOAuthScopes:
          - openid
          - profile
          - email
          - aws.cognito.signin.user.admin
        CallbackURLs:
          - "https://www-${opt:stage}.indyauction.net/
          - "https://www-${opt:stage}.indyauction.net/login
          - "https://www-${opt:stage}.indyauction.net/register"
          - "http://localhost:3000/"
          - "http://localhost:3001/"
          - "http://localhost:3000/login"
          - "http://localhost:3000/register"
        LogoutURLs:
          - "https://www-${opt:stage}.indyauction.net/
          - "https://www-${opt:stage}.indyauction.net/login
          - "https://www-${opt:stage}.indyauction.net/register"
          - "http://localhost:3000/"
          - "http://localhost:3001/"
          - "http://localhost:3000/login"
          - "http://localhost:3000/register"
        IdTokenValidity: 60
        PreventUserExistenceErrors: ENABLED
        RefreshTokenValidity: 30
        TokenValidityUnits:
          AccessToken: minutes
          IdToken: minutes
          RefreshToken: days
        ReadAttributes:
          - "address"
          - "birthdate"
          - "email"
          - "email_verified"
          - "family_name"
          - "gender"
          - "given_name"
          - "locale"
          - "middle_name"
          - "name"
          - "nickname"
          - "phone_number"
          - "phone_number_verified"
          - "picture"
          - "preferred_username"
          - "profile"
          - "updated_at"
          - "website"
          - "zoneinfo"

        WriteAttributes:
          - "address"
          - "birthdate"
          - "email"
          - "family_name"
          - "gender"
          - "given_name"
          - "locale"
          - "middle_name"
          - "name"
          - "nickname"
          - "phone_number"
          - "picture"
          - "preferred_username"
          - "profile"
          - "updated_at"
          - "website"
          - "zoneinfo"

    
    CognitoIdentityPool:
      Type: AWS::Cognito::IdentityPool
      Properties:
        IdentityPoolName: indyauction-buyers-${self:provider.stage}
        AllowUnauthenticatedIdentities: true
        AllowClassicFlow: true
        CognitoIdentityProviders: 
          - ClientId: !Ref BuyerUsersClient
            ProviderName: !GetAtt BuyerUsers.ProviderName
            ServerSideTokenCheck: false
        # Define more configuration properties as needed

    CognitoIdentityPoolRole:
      Type: AWS::Cognito::IdentityPoolRoleAttachment
      Properties:
        IdentityPoolId:
          Ref: CognitoIdentityPool
        Roles:
          authenticated:
            Fn::GetAtt: [MyRoleLogicalName, Arn] # Replace with your IAM role
    
    MyRoleLogicalName: # Define your IAM role here
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: "Allow"
              Principal:
                Federated: "cognito-identity.amazonaws.com"
              Action: "sts:AssumeRoleWithWebIdentity"
              Condition:
                StringEquals:
                  "cognito-identity.amazonaws.com:aud": 
                    Ref: CognitoIdentityPool
                "ForAnyValue:StringLike":
                  "cognito-identity.amazonaws.com:amr": "authenticated"

        Policies:
          - PolicyName: S3AccessPolicy
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: "Allow"
                  Action:
                    - "s3:*" # Adjust permissions as needed
                  Resource: "arn:aws:s3:::${ssm:BUCKET_NAME}" # Replace with your S3 bucket ARN
  
    AdminCognitoIdentityPoolIDStore:
        Type: AWS::SSM::Parameter
        Properties:
          Name: ADMIN_COGNITO_IDENTITY_POOL_ID
          Type: String
          Value: { Ref: CognitoIdentityPool }

    AdminCognitoPoolIDStore:
        Type: AWS::SSM::Parameter
        Properties:
          Name: ADMIN_COGNITO_USERPOOL_ID
          Type: String
          Value: { Ref: BuyerUsers }

    AdminCognitoPoolNameStore:
        Type: AWS::SSM::Parameter
        Properties:
          Name: ADMIN_COGNITO_USERPOOL_NAME
          Type: String
          Value: indyauction-buyers-${self:provider.stage}
    AdminCognitoClientIDStore:
        Type: AWS::SSM::Parameter
        Properties:
          Name: ADMIN_COGNITO_CLIENT_ID
          Type: String
          Value: { Ref: BuyerUsersClient }
    
    AdminCognitoPoolARNStore:
        Type: AWS::SSM::Parameter
        Properties:
          Name: ADMIN_COGNITO_AUTH_ARN
          Type: String
          Value:
            Fn::GetAtt:
              - BuyerUsers
              - Arn

    UserLogin:
      Type: AWS::Pinpoint::EmailTemplate
      Properties: 
        HtmlPart: ${file(./templates/login_email.html)}
        Subject: Indy Auction - OTP Verification for Your Account
        TemplateName: ${self:provider.stage}-user-login



        AliasAttributes:
          - preferred_username
        # AliasAttributes:
        #   - email
        # UsernameAttributes: 
        #   - email
        VerificationMessageTemplate:
          DefaultEmailOption: CONFIRM_WITH_CODE
        UserAttributeUpdateSettings:
          AttributesRequireVerificationBeforeUpdate: []
        MfaConfiguration: "OFF"
        # EnabledMfas:
        #   - SOFTWARE_TOKEN_MFA
        EmailConfiguration:
          EmailSendingAccount: COGNITO_DEFAULT
        UsernameConfiguration:
          CaseSensitive: true
        AccountRecoverySetting:
          RecoveryMechanisms:
            - Priority: 1
              Name: admin_only
    
custom:
  packageExternal:
    external:
      - '../lib'
      - '../entities'

plugins:
  - serverless-offline
  - serverless-package-external
