const mongoose = require('mongoose')
const Schema = mongoose.Schema

const UserSchema = new Schema({
    userFirstName: {
        type: String, required: false, index: true, default: '',
    },
    userLastName: {
        type: String, required: false, index: true, default: '',
    },
    userImageUrl: { type: String, required: false, index: true },
    location: { // For updating partner location currently taking from user update loc api need to be updated from partner update
        type: { type: String },
        coordinates: [Number],
    },
    appleUserId: {
        type: String, required: false, index: true, default: '',
    },
    userEmailId: {
        type: String, required: true, trim: true, index: true, lowercase: true,
    },
    userCountryData: {
        countryId: { type: String, trim: true },
        countryName: { type: String, trim: true, index: true },
        countryISDCode: { type: Number },
        countryCode: { type: String },
        currency: { type: String, required: false, default: 'USD' },
        currencySymbol: { type: String, required: false, default: '$' },
    },
    userMobileNo: {
        type: Number, required: false, trim: true, index: true,
    },
    userIsPartner: {
        type: Boolean, required: false, default: false, index: true,
    },
    userAddress: {
        addressLine1: { type: String, required: false, trim: true },
        addressLine2: { type: String, required: false, trim: true },
        addressZipcode: { type: String, required: false },
        addressLatLongAvailable: { type: Boolean, default: false, required: false },
        addressLatitude: { type: Number, required: false },
        addressLongitude: { type: Number, required: false },
        state: { type: String, required: false },
        city: { type: String, required: false },
    },
    userPartnerCommercialName: { type: String, required: false },
    partnerDeactivate: { type: Boolean, default: false },
    userPartnerInfo: {
        isCertified: { type: Boolean, default: false },
        partnerEarnings: { type: Number, required: false },
        partnerCommercialName: { type: String, required: false },
        partnerLegalRep: { type: String, required: false },
        partnerAboutService: { type: String, required: false },
        partnerImageUrl: { type: String, index: true, required: false },
        partnerDocumentUrl: { type: String, required: false },
        partnerEmailId: { type: String, required: false },
        partnerMobileNo: { type: Number, required: false, default: null },
        partnerAccountType: { type: Number, default: 0 },
        partnerWebsite: { type: String, required: false, default: '' },
        partnerDocumentNo: { type: String, required: false },
        partnerIsVeterinarian: { type: Boolean, default: false, required: false },
        stripePayout: { type: Boolean, default: false, required: false },
        payPalPayout: { type: Boolean, default: false, required: false },
        partnerTags: { type: Array, required: false, unique: true },
        googleCalConnectionStatus: { type: Boolean, default: false, required: false },
        iCalConnectionStatus: { type: Boolean, default: false, required: false },
        partnerCalendarAuthCredentials: {
            access_token: { type: String, required: false },
            refresh_token: { type: String, required: false },
            scope: { type: String, required: false },
            token_type: { type: String, required: false },
            expiry_date: { type: Date, required: false },
        },
        partnerAvailability: {
            monday: {
                status: { type: Boolean, default: false, required: false },
                start_time: { type: Date, required: false },
                end_time: { type: Date, required: false },
            },
            tuesday: {
                status: { type: Boolean, default: false, required: false },
                start_time: { type: Date, required: false },
                end_time: { type: Date, required: false },
            },
            wednesday: {
                status: { type: Boolean, default: false, required: false },
                start_time: { type: Date, required: false },
                end_time: { type: Date, required: false },
            },
            thursday: {
                status: { type: Boolean, default: false, required: false },
                start_time: { type: Date, required: false },
                end_time: { type: Date, required: false },
            },
            friday: {
                status: { type: Boolean, default: false, required: false },
                start_time: { type: Date, required: false },
                end_time: { type: Date, required: false },
            },
            saturday: {
                status: { type: Boolean, default: false, required: false },
                start_time: { type: Date, required: false },
                end_time: { type: Date, required: false },
            },
            sunday: {
                status: { type: Boolean, default: false, required: false },
                start_time: { type: Date, required: false },
                end_time: { type: Date, required: false },
            },
        },
        partnerAddress: {
            addressLine1: { type: String, required: false, trim: true },
            addressLine2: { type: String, required: false, trim: true },
            addressZipcode: { type: String, required: false },
            addressLatLongAvailable: { type: Boolean, default: false, required: false },
            addressLatitude: { type: Number, required: false },
            addressLongitude: { type: Number, required: false },
            state: { type: String, required: false },
            city: { type: String, required: false },
        },
        deactivateReason: { type: String, required: false },
        partnerServiceIds: { type: Array, required: false },
        partnerQuizIds: { type: Array, required: false },
        partnerCalenderEventIds: { type: Array, required: false },
        partnerCertificateIds: { type: Array, required: false },
        partnerTrainingIds: { type: Array, required: false },
        partnerAvgRating: { type: Number, required: false, default: 0 },
        partnerVerified: { type: Boolean, default: false, index: true },
    },
    userEmailVerified: { type: Boolean, default: true },
    adminUser: { type: Boolean, default: false },
    partnerPenaltyAmount: { type: Number, required: false, default: 0 },
    accumulatedPoints: { type: String, required: false },
    userPassword: { type: String, required: false, trim: true },
    userLoginType: { type: Number, required: false },
    stripeConnectId: { type: String, required: false },
    userLoginToken: { type: String, required: false },
    facebookLoginToken: { type: String, required: false },
    googleLoginToken: { type: String, required: false },
    userReferredCode: { type: String, required: false },
    userReferralCode: {
        type: String, required: false, index: true, default: '',
    },
    userDeviceType: {
        type: Number, required: false, index: true,
    },
    userDeviceId: { type: String, required: false, index: true },
    userFCMToken: { type: String, required: false, index: true },
    userLastScene: { type: Date, default: Date.now, index: true },
    userStatus: { type: Number, default: 1, index: true },
    userPasswordSet: { type: Boolean, index: true, required: false },
    userPasswordToken: {
        type: String, required: false, trim: true, index: true,
    },
    userVerificationToken: { type: String, required: false },
    userLanguage: { type: Number, default: 0 },
    createdAt: { type: Date, default: Date.now, index: true },
    userType: { type: String, required: false, index: true },
    updatedAt: { type: Date, default: Date.now },
    welcomePush: { type: Boolean, required: false, default: false },
    userPhoneNumberVerified: { type: Boolean, required: false, default: false },
    deleted: { type: Boolean, default: false },
    stripeConnectedAccountId: { type: String, default: null, required: false },
})

let User = mongoose.model('User', UserSchema)
module.exports = User
