service: lot-bid-history
frameworkVersion: '3'
useDotenv: true
deprecationNotificationMode: error
disabledDeprecations:
  - UNSUPPORTED_CLI_OPTIONS
  - CLI_OPTIONS_SCHEMA_V3
  - CONFIG_VALIDATION_MODE_DEFAULT_V3
  - 
provider:
  name: aws
  endpointType: REGIONAL
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  region: eu-west-2
  versionFunctions: false
  layers: ${ssm:COMMON_LIB_ARN}
  environment:
    TABLE_NAME: ${opt:stage, self:provider.stage}-${self:service}
    COGNITO_USER_POOL_ID: ${ssm:SELLER_COGNITO_USERPOOL_ID}
    COGNITO_SELLER_CLIENT_ID: ${ssm:SELLER_COGNITO_CLIENT_ID}
    SELLERS_TABLE: ${opt:stage, self:provider.stage}-users
    REGION: ${env:REGION}
    DATABASE: ${ssm:DATABASE}
    STAGE: ${opt:stage, self:provider.stage}
    MONGODB_NAME: ${opt:stage, self:provider.stage}
    MONGODB_COLLECTION_NAME: ${opt:stage, self:provider.stage}-users
    MONGO_CLIENT: ${self:custom.mongodbConnectionString}
    LOT_COLLECTION_NAME: ${opt:stage, self:provider.stage}-bid-informations
    UNIQUE_BIDDERS_COLLECTIONS: ${opt:stage, self:provider.stage}-unique-bids
    REGISTER_AUCTION_COLLECTION: ${opt:stage, self:provider.stage}-register-auction
    SENDER_EMAIL_ADDRESS: ${ssm:SENDER_EMAIL_ADDRESS}
    BUCKET_NAME: ${ssm:BUCKET_NAME}
    CSV_FILE:  /tmp/Auctions.csv
    S3_BUCKET: ${ssm:BUCKET_NAME}
    CDN_LINK: ${ssm:CDN_URL}
    SUMSUB_SECRET_KEY: ${ssm:SUMSUB_SECRET_KEY}
    SUMSUB_APP_TOKEN: ${ssm:SUMSUB_APP_TOKEN}
    REDIS_CLUSTER_ENDPOINT: ${ssm:REDIS_CLUSTER_ENDPOINT}
    MAILCHIMP_SECRET_KEY: ${ssm:MAILCHIMP_SECRET_KEY}

  http:
    cors: true
    authorizers:
      cognito-auth:
        identitySource: $request.header.Authorization
        issuerUrl: https://cognito-idp.${env:REGION}.amazonaws.com/${ssm:SELLER_COGNITO_USERPOOL_ID}
        audience: ${ssm:SELLER_COGNITO_CLIENT_ID}

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - cognito-idp:*
            - ses:*
            - s3:*
            - lambda:*
            - mobiletargeting:*
          Resource: "*"
 
package:
  patterns:
    - '!./node_modules/**'
    - ./handlers/**
    - ./data/**
    - ./entities/**
    - ./utils/**
    - ./lib/**

custom:
  isProd: ${self:provider.stage} # Will be resolved at deploy time
  mongodbConnectionString: ${file(../env.yml):${self:provider.stage}.MONGODB_CONNECTION_STRING}
  packageExternal:
    external:
      - '../../lib'
      - '../../entities'
      
  customDomain:
    rest:
      domainName: ${ssm:DOMAIN_NAME}
      stage: ${opt:stage, self:provider.stage}
      basePath: v1/${self:service}
      certificateName: ${ssm:DOMAIN_CERTIFICATE}
      createRoute53Record: true
      securityPolicy: tls_1_2
      endpointType: REGIONAL
  serverlessIfElse:
    - If: '${param:offline, "false"} == true'
      Set:
        provider.environment.MONGO_CLIENT: ${env:MONGODB_CONNECTION_STRING}

functions: 
  list-bids:
    handler: handlers/list.handler
    layers:
      - ${ssm:COMMON_LIB_ARN}
    vpc:
      securityGroupIds:
        - ${ssm:SECURITY_GROUP_ID}
      subnetIds:
        - ${ssm:SUBNET_ID}
    events:
      - http:
          cors: true
          path: /{lot_id}
          method: GET
          authorizer:
            arn: ${ssm:SELLER_COGNITO_AUTH_ARN}

  buyer-list-bids:
    handler: handlers/list.handler
    layers:
      - ${ssm:COMMON_LIB_ARN}
    vpc:
      securityGroupIds:
        - ${ssm:SECURITY_GROUP_ID}
      subnetIds:
        - ${ssm:SUBNET_ID}
    events:
      - http:
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Requested-With
              - Accept
              - Access-Control-Allow-Headers
          path: /buyer/{lot_id}
          method: GET
          authorizer: ${ssm:BUYER_COGNITO_AUTH_ARN}      #arn:aws:lambda:${aws:region}:${aws:accountId}:function:lambda-authorizer-${self:provider.stage}-lambda-authorizer
            
  bid-listing:
    handler: handlers/bid_list.list_bids
    timeout: 60
    runtime: python3.10
    layers:
    - ${ssm:COMMON_LIB_ARN_PYTHON}
    vpc:
      securityGroupIds:
      - ${ssm:SECURITY_GROUP_ID}
      subnetIds:
      - ${ssm:SUBNET_ID}
    events:
      - http:
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Requested-With
              - Accept
              - Access-Control-Allow-Headers
          path: /seller/bids
          method: get
          authorizer:
              arn: ${ssm:SELLER_COGNITO_AUTH_ARN}
  
 
plugins:
  - serverless-offline
  - serverless-package-external
  - serverless-domain-manager
  - serverless-plugin-ifelse
