service: orders
frameworkVersion: '3'
useDotenv: true
deprecationNotificationMode: error
disabledDeprecations:
  - UNSUPPORTED_CLI_OPTIONS
  - CLI_OPTIONS_SCHEMA_V3
  - CONFIG_VALIDATION_MODE_DEFAULT_V3
  - 
provider:
  name: aws
  endpointType: REGIONAL
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  region: eu-west-2
  versionFunctions: false
  layers: ${ssm:COMMON_LIB_ARN}
  environment:
    TABLE_NAME: ${opt:stage, self:provider.stage}-${self:service}
    COGNITO_USER_POOL_ID: ${ssm:SELLER_COGNITO_USERPOOL_ID}
    COGNITO_SELLER_CLIENT_ID: ${ssm:SELLER_COGNITO_CLIENT_ID}
    REGION: ${ssm:REGION}
    STAGE: ${opt:stage, self:provider.stage}
    DATABASE: ${opt:stage, self:provider.stage}
    MONGODB_NAME: ${opt:stage, self:provider.stage}
    MONGODB_COLLECTION_NAME: ${opt:stage, self:provider.stage}-users
    MONGO_CLIENT: ${ssm:MONGODB_CONNECTION_STRING}
    AUCTION_MONGODB_COLLECTION_NAME: ${opt:stage, self:provider.stage}-auctions
    COGNITO_USER_POOL: ${ssm:SELLER_COGNITO_USERPOOL_NAME}
    SELLERS_TABLE: ${opt:stage, self:provider.stage}-users
    SUMSUB_SECRET_KEY: ${ssm:SUMSUB_SECRET_KEY}
    SUMSUB_APP_TOKEN: ${ssm:SUMSUB_APP_TOKEN}
    CSV_FILE: ${ssm:CSV_FILE}
    S3_BUCKET:  ${ssm:BUCKET_NAME}
    LOT_COLLECTION_NAME: ${opt:stage, self:provider.stage}-lots
    COUNTER_LOT: ${opt:stage, self:provider.stage}-counters
    REGISTER_AUCTION_COLLECTION: ${opt:stage, self:provider.stage}-register-auction
    SUB_DOMAIN_TABLE: ${opt:stage, self:provider.stage}-subdomain
    USERPOOLS_MONGO: ${opt:stage, self:provider.stage}-userpools
    #KMS_KEY_ID: ${ssm:KMS_KEY_ID}
    BUYER_EMAIL_OTP_TEMPLATE: 
      Fn::Join:
        - ":"
        - - "arn"
          - "aws"
          - "mobiletargeting"
          - !Ref "AWS::Region"
          - !Ref "AWS::AccountId"
          - "templates/${self:provider.stage}-buyer_email_otp/EMAIL"
         
    ENCRYPTION_SECRET_KEY: ${ssm:ENCRYPTION_SECRET_KEY}
    BUYER_COLLECTION: ${opt:stage, self:provider.stage}-buyers
    RECAPTCHA_KEY: ${ssm:RECAPTCHA_KEY}
    RECAPTCHA_URL: ${ssm:RECAPTCHA_URL}
    CUSTOMER_SESSION_TOKEN_SECRET: ${ssm:CUSTOMER_SESSION_TOKEN_SECRET}
    SES_SENDER_EMAIL_ID: ${ssm:SENDER_EMAIL}
    DEFAULT_SUB_DOMAIN: ${ssm:DEFAULT_SUB_DOMAIN} 
    JWT_SECRET_KEY: ${ssm:JWT_SECRET_KEY}
    TEMPLATE_ARN_EMAIL_RESET_PASSWORD:  
      Fn::Join:
        - ":"
        - - "arn"
          - "aws"
          - "mobiletargeting"
          - !Ref "AWS::Region"
          - !Ref "AWS::AccountId"
          - "templates/${self:provider.stage}-buyer_reset_password/EMAIL"
       
   
    BASE_URL_BUYER: ${ssm:DEFAULT_SUB_DOMAIN}
    CDN_LINK: ${ssm:CDN_URL}
    STRIPE_API_KEY: ${ssm:STRIPE_API_KEY}
    SELLER_GOOGLE_PASSWORD: ${ssm:SELLER_GOOGLE_PASSWORD}
    PASSWORD_SECRET_KEY: ${ssm:PASSWORD_SECRET_KEY}
    CART_COLLECTION: ${opt:stage, self:provider.stage}-carts
    ORDERS_COLLECTION: ${opt:stage, self:provider.stage}-orders
    SALES_CSV_FILE: ${ssm:SALES_CSV_FILE}
    REDIS_CLUSTER_ENDPOINT: ${ssm:REDIS_CLUSTER_ENDPOINT}
    
  http:
    cors: true
     

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - cognito-idp:*
            - ses:*
            - s3:*
            - lambda:*
            - mobiletargeting:*
            - dynamodb:*
            - execute-api:*
          Resource: "*"
 
package:
  patterns:
    - '!./node_modules/**'
    - ./handlers/**
    - ./data/**
    - ./entities/**
    - ./utils/**
    - ./lib/**

custom:
  packageExternal:
    external:
      - '../../lib'
      - '../../entities'
      
  customDomain:
    rest:
      domainName: ${ssm:DOMAIN_NAME}
      stage: ${opt:stage, self:provider.stage}
      basePath: v1/${self:service}
      certificateName: ${ssm:DOMAIN_CERTIFICATE}
      createRoute53Record: true
      securityPolicy: tls_1_2
      endpointType: REGIONAL
  serverlessIfElse:
    - If: '${param:offline, "false"} == true'
      Set:
        provider.environment.MONGO_CLIENT: ${env:MONGODB_CONNECTION_STRING}

functions:
  list_orders:
    handler: handlers/list.list_orders
    runtime: python3.8
    layers:
      - ${ssm:COMMON_LIB_ARN_PYTHON}
    vpc:
      securityGroupIds:
        - ${ssm:SECURITY_GROUP_ID}
      subnetIds:
        - ${ssm:SUBNET_ID}
    events:
      - http:
          path: /
          method: get
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Requested-With
              - Accept
              - Access-Control-Allow-Headers
          authorizer: arn:aws:lambda:${ssm:REGION}:${ssm:ACCOUNT_ID}:function:lambda-authorizer-${self:provider.stage}-lambda-authorizer
  
  order_detail:
    handler: handlers/order_detail.order_detail
    runtime: python3.8
    layers:
      - ${ssm:COMMON_LIB_ARN_PYTHON}
    vpc:
      securityGroupIds:
        - ${ssm:SECURITY_GROUP_ID}
      subnetIds:
        - ${ssm:SUBNET_ID}
    events:
      - http:
          path: /details
          method: get
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Requested-With
              - Accept
              - Access-Control-Allow-Headers
          authorizer: arn:aws:lambda:${ssm:REGION}:${ssm:ACCOUNT_ID}:function:lambda-authorizer-${self:provider.stage}-lambda-authorizer
  sales_details:
    handler: handlers/sales_details.sales_details
    runtime: python3.8
    layers:
      - ${ssm:COMMON_LIB_ARN_PYTHON}
    vpc:
      securityGroupIds:
        - ${ssm:SECURITY_GROUP_ID}
      subnetIds:
        - ${ssm:SUBNET_ID}
    events:
      - http:
          path: /sales
          method: get
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Requested-With
              - Accept
              - Access-Control-Allow-Headers
          authorizer:
                arn: ${ssm:SELLER_COGNITO_AUTH_ARN}
          
  seller_list_orders:
    handler: handlers/sellers_list.list_orders
    runtime: python3.8
    layers:
      - ${ssm:COMMON_LIB_ARN_PYTHON}
    vpc:
      securityGroupIds:
        - ${ssm:SECURITY_GROUP_ID}
      subnetIds:
        - ${ssm:SUBNET_ID}
    events:
      - http:
          path: /seller
          method: get
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Requested-With
              - Accept
              - Access-Control-Allow-Headers
          authorizer:
              arn: ${ssm:SELLER_COGNITO_AUTH_ARN}

resources:
   Resources:
    GatewayResponseDefault4XX:
       Type: 'AWS::ApiGateway::GatewayResponse'
       Properties:
         ResponseParameters:
           gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
           gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
         ResponseType: DEFAULT_4XX
         RestApiId:
           Ref: 'ApiGatewayRestApi'
    
    # BuyerEmailOtp:
    #   Type: AWS::Pinpoint::EmailTemplate
    #   Properties: 
    #     HtmlPart: ${file(./templates/buyer_email_otp.html)}
    #     Subject: Indy.auction - OTP Verification for Your Account
    #     TemplateName: ${self:provider.stage}-buyer_email_otp
    
    # BuyerResetPassword:
    #   Type: AWS::Pinpoint::EmailTemplate
    #   Properties: 
    #     HtmlPart: ${file(./templates/buyer_reset_password.html)}
    #     Subject: Indy.auction- Reset your password
    #     TemplateName: ${self:provider.stage}-buyer_reset_password

plugins:
  - serverless-offline
  - serverless-package-external
  - serverless-domain-manager
  - serverless-plugin-ifelse