service: lambda-authorizer
frameworkVersion: '3'
useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  region: eu-west-2
  environment:
    STAGE: ${self:provider.stage}
    REGION: ${env:REGION}
    SELLER_GOOGLE_PASSWORD: INDY@SELLER
    BUYER_COLLECTION: ${opt:stage, self:provider.stage}-buyers
    MONGO_CLIENT: ${self:custom.mongodbConnectionString}
    DATABASE: ${opt:stage, self:provider.stage}
    

  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
             - lambda:*
             - execute-api:*
          Resource: "*"
                 
package:
   patterns:
    - '!./node_modules/**'
    - ./handlers/**
    - ./data/**
    - ./entities/**
    - ./utils/**
    - ./lib/**
    - ./assets/**

custom:
  mongodbConnectionString: ${file(../env.yml):${self:provider.stage}.MONGODB_CONNECTION_STRING}
  packageExternal:
    external:
      - '../../lib'
      - '../../entities'
  
serverlessIfElse:
    - If: '${param:offline, "false"} == true'
      Set:
        provider.environment.MONGO_CLIENT: ${env:MONGODB_CONNECTION_STRING}

functions:
  lambda-authorizer:
    handler: handlers/auth.handler
    vpc:
      securityGroupIds:
        - ${ssm:SECURITY_GROUP_ID}
      subnetIds:
        - ${ssm:SUBNET_ID}
    layers:
      - ${ssm:LAMBDA_AUTH_LIB_NODE_ARN}


resources:
   Resources:
     UserPoolInvokePreAuth:
      Type: AWS::Lambda::Permission
      Properties:
        Action: lambda:invokeFunction
        Principal: cognito-idp.amazonaws.com
        FunctionName: arn:aws:lambda:${aws:region}:${aws:accountId}:function:cognito-${self:provider.stage}-pre-auth
        SourceArn: arn:aws:cognito-idp:${aws:region}:${aws:accountId}:userpool/${ssm:BUYER_COGNITO_USERPOOL_ID}


plugins:
  - serverless-package-external
  - serverless-offline