service: buyers
frameworkVersion: '3'
useDotenv: true
deprecationNotificationMode: error
disabledDeprecations:
  - UNSUPPORTED_CLI_OPTIONS
  - CLI_OPTIONS_SCHEMA_V3
  - CONFIG_VALIDATION_MODE_DEFAULT_V3
  - 
provider:
  name: aws
  endpointType: REGIONAL
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  region: ${env:REGION}
  versionFunctions: false
  layers: ${env:COMMON_LIB_ARN}
  environment:
    BUYER_RECAPTCHA_URL: ${env:BUYER_RECAPTCHA_URL}
    BUYER_RECAPTCHA_KEY: ${env:BUYER_RECAPTCHA_KEY}
    TABLE_NAME: ${opt:stage, self:provider.stage}-${self:service}
    BUYER_WISHLIST_TABLE_NAME: ${env:BUYER_WISHLIST_TABLE_NAME}
    COGNITO_USER_POOL_ID: ${env:COGNITO_USER_POOL_ID}
    COGNITO_SELLER_CLIENT_ID: ${env:COGNITO_SELLER_CLIENT_ID}
    REGION: ${env:REGION}
    STAGE: ${opt:stage, self:provider.stage}
    DATABASE: ${env:DATABASE}
    MONGODB_NAME: ${env:MONGODB_NAME}
    MONGODB_COLLECTION_NAME: ${env:MONGODB_COLLECTION_NAME}
    MONGO_CLIENT: ${env:MONGO_CLIENT}
    AUCTION_MONGODB_COLLECTION_NAME: ${env:AUCTION_MONGODB_COLLECTION_NAME}
    COGNITO_USER_POOL: ${env:COGNITO_USER_POOL}
    SELLERS_TABLE: ${opt:stage, self:provider.stage}-users
    SUMSUB_SECRET_KEY: ${env:SUMSUB_SECRET_KEY}
    SUMSUB_APP_TOKEN: ${env:SUMSUB_APP_TOKEN}
    CSV_FILE: ${env:CSV_FILE}
    S3_BUCKET: ${env:S3_BUCKET}
    LOT_COLLECTION_NAME: ${env:LOT_COLLECTION_NAME}
    COUNTER_LOT: ${env:COUNTER_LOT}
    REGISTER_AUCTION_COLLECTION: ${env:REGISTER_AUCTION_COLLECTION}
    SUB_DOMAIN_TABLE: ${env:SUB_DOMAIN_TABLE}
    USERPOOLS_MONGO: ${env:USERPOOLS_MONGO}
    KMS_KEY_ID: ${env:KMS_KEY_ID}
    BUYER_EMAIL_OTP_TEMPLATE: ${env:BUYER_EMAIL_OTP_TEMPLATE}
    ENCRYPTION_SECRET_KEY: ${env:ENCRYPTION_SECRET_KEY}
    BUYER_COLLECTION: ${env:BUYER_COLLECTION}
    RECAPTCHA_KEY: ${env:RECAPTCHA_KEY}
    RECAPTCHA_URL: ${env:RECAPTCHA_URL}
    CUSTOMER_SESSION_TOKEN_SECRET: ${env:CUSTOMER_SESSION_TOKEN_SECRET}
    SENDER_EMAIL_ADDRESS: ${env:SENDER_EMAIL_ADDRESS}
    DEFAULT_SUB_DOMAIN: ${env:DEFAULT_SUB_DOMAIN}
    BUYER_AUCTION_REGISTER_TEMPLATE: #${env:BUYER_AUCTION_REGISTER_TEMPLATE}
      Fn::GetAtt:
      - "sesTemplate"
      - "Arn"
    
    JWT_SECRET_KEY: ${env:JWT_SECRET_KEY}
    TEMPLATE_ARN_EMAIL_RESET_PASSWORD: ${env:TEMPLATE_ARN_EMAIL_RESET_PASSWORD}
    BASE_URL_BUYER: ${env:BASE_URL_BUYER}
    CDN_LINK: ${env:CDN_LINK}
    DEFAULT_USERPOOL_ID: ${env:DEFAULT_USERPOOL_ID}
    DEFAULT_COGNITO_DOMAIN: ${env:DEFAULT_COGNITO_DOMAIN}
    STRIPE_API_KEY: ${env:STRIPE_API_KEY}
    CREDIT_CARD_STRIPE_API_KEY: ${env:CREDIT_CARD_STRIPE_API_KEY}
    SELLER_GOOGLE_PASSWORD: ${env:SELLER_GOOGLE_PASSWORD}
    PASSWORD_SECRET_KEY: ${env:PASSWORD_SECRET_KEY}
    
  http:
    cors: true
    authorizers:
      cognito-auth:
        identitySource: $request.header.Authorization
        issuerUrl: https://cognito-idp.${env:REGION}.amazonaws.com/${env:COGNITO_USER_POOL_ID}
        audience: ${env:COGNITO_SELLER_CLIENT_ID}

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - cognito-idp:*
            - ses:*
            - s3:*
            - lambda:*
            - mobiletargeting:*
            - dynamodb:*
            - execute-api:*
          Resource: "*"
 
package:
  patterns:
    - '!./node_modules/**'
    - ./handlers/**
    - ./data/**
    - ./entities/**
    - ./utils/**
    - ./lib/**

custom:
  packageExternal:
    external:
      - '../../lib'
      - '../../entities'
      
  customDomain:
    rest:
      domainName: ${env:DOMAIN_NAME}
      stage: ${opt:stage, self:provider.stage}
      basePath: ${opt:stage, self:provider.stage}/v1/${self:service}
      certificateName: ${env:DOMAIN_CERTIFICATE}
      createRoute53Record: true
      securityPolicy: tls_1_2
      endpointType: REGIONAL

functions: 

  view:
    handler: handlers/view.view
    runtime: python3.8
    layers:
      - ${env:COMMON_PYTHON_LIB_ARN}
    vpc:
      securityGroupIds:
        - sg-0882c1da39e729097
      subnetIds:
        - subnet-0ff05c7c2bd2a3f87
    events:
      - http:
          cors: true
          path: /view
          method: get
          
  create_userpools:
    handler: handlers/userpool.create
    runtime: python3.8
    layers:
      - ${env:COMMON_PYTHON_LIB_ARN}
    vpc:
      securityGroupIds:
        - sg-0882c1da39e729097
      subnetIds:
        - subnet-0ff05c7c2bd2a3f87
    events:
      - http:
          cors: true
          path: /
          method: get

  verify-recaptha:
    handler: handlers/verify_the_recaptcha.verify
    runtime: python3.8
    layers:
      - ${env:COMMON_PYTHON_LIB_ARN}
    vpc:
      securityGroupIds:
        - sg-0882c1da39e729097
      subnetIds:
        - subnet-0ff05c7c2bd2a3f87
    events:
      - http:
          path: /verify-captcha
          method: post
          cors: true

  otp-validation:
    handler: handlers/otp_validation.validate
    runtime: python3.8
    layers:
      - ${env:COMMON_PYTHON_LIB_ARN}
      - ${env:ENCRYPTION_LAYER}
    vpc:
      securityGroupIds:
        - sg-0882c1da39e729097
      subnetIds:
        - subnet-0ff05c7c2bd2a3f87
    events:
      - http:
          path: /otp-validation
          method: post
          cors: true

  view_lots:
    handler: handlers/view_list_lots.view_list_lots
    runtime: python3.8
    layers:
    - ${env:COMMON_PYTHON_LIB_ARN}
    vpc:
      securityGroupIds:
      - sg-0882c1da39e729097
      subnetIds:
      - subnet-0ff05c7c2bd2a3f87
    events:
      - http:
          cors: true
          path: /view-lots
          method: get
  
  search_lots:
    handler: handlers/search_lots.lot_search
    runtime: python3.8
    layers:
    - ${env:COMMON_PYTHON_LIB_ARN}
    vpc:
      securityGroupIds:
      - sg-0882c1da39e729097
      subnetIds:
      - subnet-0ff05c7c2bd2a3f87
    events:
      - http:
          cors: true
          path: /search-lots
          method: get

              
  view_lot_details:
    handler: handlers/view_lots.lot_details
    runtime: python3.8
    layers:
    - ${env:COMMON_PYTHON_LIB_ARN}
    vpc:
      securityGroupIds:
      - sg-0882c1da39e729097
      subnetIds:
      - subnet-0ff05c7c2bd2a3f87
    events:
      - http:
          cors: true
          path: /lot-details
          method: get
          
  credit_card:
    handler: handlers/credit_card.credit_card
    runtime: python3.8
    layers:
    - ${env:COMMON_PYTHON_LIB_ARN}
    vpc:
      securityGroupIds:
      - sg-0882c1da39e729097
      subnetIds:
      - subnet-0ff05c7c2bd2a3f87
    events:
      - http:
          cors: true
          path: /verify-card
          method: post

  acceting_buyer:
      handler: handlers/accept_buyer.accept_buyer
      runtime: python3.8
      layers:
      - ${env:COMMON_PYTHON_LIB_ARN}
      vpc:
        securityGroupIds:
        - sg-0882c1da39e729097
        subnetIds:
        - subnet-0ff05c7c2bd2a3f87
      events:
        - http:
            cors: true
            path: /approval
            method: patch
            authorizer:
              arn: ${env:COGNITO_AUTH_ARN}
  
  update_password:
    handler: handlers/update_password.update_password
    runtime: python3.8
    layers:
    - ${env:COMMON_PYTHON_LIB_ARN}
    vpc:
      securityGroupIds:
      - sg-0882c1da39e729097
      subnetIds:
      - subnet-0ff05c7c2bd2a3f87
    events:
      - http:
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Requested-With
              - Accept
              - Access-Control-Allow-Headers
          authorizer: arn:aws:lambda:${env:REGION}:${env:AWS_ACCOUNT_ID}:function:lambda-authorizer-${self:provider.stage}-lambda-authorizer
          path: /update-password
          method: post
  


  auction_register:
    handler: handlers/register_auction.register_auction
    runtime: python3.8
    layers:
      - ${env:COMMON_PYTHON_LIB_ARN}
    vpc:
      securityGroupIds:
        - sg-0882c1da39e729097
      subnetIds:
        - subnet-0ff05c7c2bd2a3f87
    events:
      - http:
          path: /auction-register
          method: get
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Requested-With
              - Accept
              - Access-Control-Allow-Headers
          authorizer: arn:aws:lambda:${env:REGION}:${env:AWS_ACCOUNT_ID}:function:lambda-authorizer-${self:provider.stage}-lambda-authorizer

  view_profile:
    handler: handlers/view_profile.view_profile
    runtime: python3.8
    layers:
    - ${env:COMMON_PYTHON_LIB_ARN}
    vpc:
      securityGroupIds:
      - sg-0882c1da39e729097
      subnetIds:
      - subnet-0ff05c7c2bd2a3f87
    events:
      - http:
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Requested-With
              - Accept
              - Access-Control-Allow-Headers
          path: /profile
          method: patch
          authorizer: arn:aws:lambda:${env:REGION}:${env:AWS_ACCOUNT_ID}:function:lambda-authorizer-${self:provider.stage}-lambda-authorizer
  
  add_address:
    handler: handlers/add_address.add_address
    runtime: python3.8
    layers:
    - ${env:COMMON_PYTHON_LIB_ARN}
    vpc:
      securityGroupIds:
      - sg-0882c1da39e729097
      subnetIds:
      - subnet-0ff05c7c2bd2a3f87
    events:
      - http:
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Requested-With
              - Accept
              - Access-Control-Allow-Headers
          path: /add-address
          method: patch
          authorizer: arn:aws:lambda:${env:REGION}:${env:AWS_ACCOUNT_ID}:function:lambda-authorizer-${self:provider.stage}-lambda-authorizer
      
  paddle_number:
    handler: handlers/get_paddle.paddle_number
    runtime: python3.8
    layers:
    - ${env:COMMON_PYTHON_LIB_ARN}
    vpc:
      securityGroupIds:
      - sg-0882c1da39e729097
      subnetIds:
      - subnet-0ff05c7c2bd2a3f87
    events:
      - http:
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Requested-With
              - Accept
              - Access-Control-Allow-Headers
          path: /paddle
          method: get
          authorizer: arn:aws:lambda:${env:REGION}:${env:AWS_ACCOUNT_ID}:function:lambda-authorizer-${self:provider.stage}-lambda-authorizer


  send-reset-link:
    handler: handlers/send_reset_link.send_reset_link
    runtime: python3.8
    layers:
      - ${env:COMMON_PYTHON_LIB_ARN}
    vpc:
      securityGroupIds:
        - sg-0882c1da39e729097
      subnetIds:
        - subnet-0ff05c7c2bd2a3f87
    events:
      - http:
          cors: true
          path: /forgot_password
          method: post

  update-new-password:
    handler: handlers/reset.password_reset
    runtime: python3.8
    layers: 
      - ${env:COMMON_PYTHON_LIB_ARN}
      - ${env:ENCRYPTION_LAYER}
    vpc:
        securityGroupIds:
          - sg-0882c1da39e729097
        subnetIds:
          - subnet-0ff05c7c2bd2a3f87
    events:
      - http:
          cors: true
          path: /reset_password
          method: post

  cognito-pre-auth:
    handler: handlers/pre_signup.handler
    vpc:
      securityGroupIds:
        - sg-0882c1da39e729097
      subnetIds:
        - subnet-0ff05c7c2bd2a3f87
    layers:
      - ${env:COMMON_LIB_ARN}
    events:
      - cognitoUserPool:
          pool: ${env:DEFAULT_USERPOOL_NAME}
          trigger: PreSignUp
          existing: true

resources:
   Resources:
     GatewayResponseDefault4XX:
       Type: 'AWS::ApiGateway::GatewayResponse'
       Properties:
         ResponseParameters:
           gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
           gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
         ResponseType: DEFAULT_4XX
         RestApiId:
           Ref: 'ApiGatewayRestApi'

     sesTemplate:
      Type: AWS::Pinpoint::EmailTemplate
      Properties:
        HtmlPart: ${file(./template/paddle.html)}
        Subject: "{{subject}}"
        TemplateDescription: Test
        TemplateName: ${opt:stage, 'dev'}_paddle
        TextPart: ${file(./template/paddle.html)}

plugins:
  - serverless-offline
  - serverless-package-external
  - serverless-domain-manager