service: buyers
frameworkVersion: '3'
useDotenv: true
deprecationNotificationMode: error
disabledDeprecations:
  - UNSUPPORTED_CLI_OPTIONS
  - CLI_OPTIONS_SCHEMA_V3
  - CONFIG_VALIDATION_MODE_DEFAULT_V3
  - 
provider:
  name: aws
  endpointType: REGIONAL
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  region: ${env:REGION}
  versionFunctions: false
  layers: ${ssm:COMMON_LIB_ARN}
  environment:
    TABLE_NAME: ${opt:stage, self:provider.stage}-${self:service}
    BUYER_WISHLIST_TABLE_NAME: ${opt:stage, self:provider.stage}-buyer-wishlists
    COGNITO_USER_POOL_ID: ${ssm:SELLER_COGNITO_USERPOOL_ID}
    COGNITO_SELLER_CLIENT_ID: ${ssm:SELLER_COGNITO_CLIENT_ID}
    REGION: ${env:REGION}
    STAGE: ${opt:stage, self:provider.stage}
    DATABASE: ${opt:stage, self:provider.stage}
    MONGODB_NAME: ${opt:stage, self:provider.stage}
    MONGODB_COLLECTION_NAME: ${opt:stage, self:provider.stage}-users
    MONGO_CLIENT: ${ssm:MONGODB_CONNECTION_STRING}
    AUCTION_MONGODB_COLLECTION_NAME: ${opt:stage, self:provider.stage}-auctions
    COGNITO_USER_POOL: ${ssm:SELLER_COGNITO_USERPOOL_NAME}
    SELLERS_TABLE: ${opt:stage, self:provider.stage}-users
    SUMSUB_SECRET_KEY: ${env:SUMSUB_SECRET_KEY}
    SUMSUB_APP_TOKEN: ${env:SUMSUB_APP_TOKEN}
    CSV_FILE: ${env:CSV_FILE}
    S3_BUCKET:  ${ssm:BUCKET_NAME}
    LOT_COLLECTION_NAME: ${opt:stage, self:provider.stage}-lots
    COUNTER_LOT: ${opt:stage, self:provider.stage}-counters
    REGISTER_AUCTION_COLLECTION: ${opt:stage, self:provider.stage}-register-auction
    SUB_DOMAIN_TABLE: ${opt:stage, self:provider.stage}-subdomain
    USERPOOLS_MONGO: ${opt:stage, self:provider.stage}-userpools
    KMS_KEY_ID: ${ssm:KMS_KEY_ID}
    BUYER_EMAIL_OTP_TEMPLATE: 
      Fn::Join:
        - ":"
        - - "arn"
          - "aws"
          - "mobiletargeting"
          - !Ref "AWS::Region"
          - !Ref "AWS::AccountId"
          - "template/${self:provider.stage}-buyer_email_otp"
          - "EMAIL"
    ENCRYPTION_SECRET_KEY: ${env:ENCRYPTION_SECRET_KEY}
    BUYER_COLLECTION: ${opt:stage, self:provider.stage}-buyers
    RECAPTCHA_KEY: ${env:RECAPTCHA_KEY}
    RECAPTCHA_URL: ${env:RECAPTCHA_URL}
    CUSTOMER_SESSION_TOKEN_SECRET: ${env:CUSTOMER_SESSION_TOKEN_SECRET}
    SENDER_EMAIL_ADDRESS: ${ssm:SENDER_EMAIL}
    DEFAULT_SUB_DOMAIN: ${ssm:DEFAULT_SUB_DOMAIN}
    BUYER_AUCTION_REGISTER_TEMPLATE: #${env:BUYER_AUCTION_REGISTER_TEMPLATE}
      Fn::GetAtt:
      - "sesTemplate"
      - "Arn"
    
    JWT_SECRET_KEY: ${env:JWT_SECRET_KEY}
    TEMPLATE_ARN_EMAIL_RESET_PASSWORD:  
      Fn::Join:
        - ":"
        - - "arn"
          - "aws"
          - "mobiletargeting"
          - !Ref "AWS::Region"
          - !Ref "AWS::AccountId"
          - "template/${self:provider.stage}-buyer_reset_password"
          - "EMAIL"
   
    BASE_URL_BUYER: ${ssm:DEFAULT_SUB_DOMAIN}
    CDN_LINK: ${ssm:CDN_URL}
    DEFAULT_USERPOOL_ID: ${ssm:BUYER_COGNITO_USERPOOL_ID}
    DEFAULT_COGNITO_DOMAIN: ${ssm:BUYER_COGNITO_USERPOOL_DOMAIN}
    STRIPE_API_KEY: ${env:STRIPE_API_KEY}
    CREDIT_CARD_STRIPE_API_KEY: ${env:CREDIT_CARD_STRIPE_API_KEY}
    SELLER_GOOGLE_PASSWORD: ${env:SELLER_GOOGLE_PASSWORD}
    PASSWORD_SECRET_KEY: ${env:PASSWORD_SECRET_KEY}
    
  http:
    cors: true
     

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - cognito-idp:*
            - ses:*
            - s3:*
            - lambda:*
            - mobiletargeting:*
            - dynamodb:*
            - execute-api:*
          Resource: "*"
 
package:
  patterns:
    - '!./node_modules/**'
    - ./handlers/**
    - ./data/**
    - ./entities/**
    - ./utils/**
    - ./lib/**

custom:
  packageExternal:
    external:
      - '../../lib'
      - '../../entities'
      
  customDomain:
    rest:
      domainName: ${ssm:DOMAIN_NAME}
      stage: ${opt:stage, self:provider.stage}
      basePath: v1/${self:service}
      certificateName: ${ssm:DOMAIN_CERTIFICATE}
      createRoute53Record: true
      securityPolicy: tls_1_2
      endpointType: REGIONAL

functions: 

  view:
    handler: handlers/view.view
    runtime: python3.8
    layers:
      - ${ssm:COMMON_LIB_ARN_PYTHON}
    vpc:
      securityGroupIds:
        - ${ssm:SECURITY_GROUP_ID}
      subnetIds:
        - ${ssm:SUBNET_ID}
    events:
      - http:
          cors: true
          path: /view
          method: get
          
  create_userpools:
    handler: handlers/userpool.create
    runtime: python3.8
    layers:
      - ${ssm:COMMON_LIB_ARN_PYTHON}
    vpc:
      securityGroupIds:
        - ${ssm:SECURITY_GROUP_ID}
      subnetIds:
        - ${ssm:SUBNET_ID}
    events:
      - http:
          cors: true
          path: /
          method: get

  verify-recaptha:
    handler: handlers/verify_the_recaptcha.verify
    runtime: python3.8
    layers:
      - ${ssm:COMMON_LIB_ARN_PYTHON}
    vpc:
      securityGroupIds:
        - ${ssm:SECURITY_GROUP_ID}
      subnetIds:
        - ${ssm:SUBNET_ID}
    events:
      - http:
          path: /verify-captcha
          method: post
          cors: true

  otp-validation:
    handler: handlers/otp_validation.validate
    runtime: python3.8
    layers:
      - ${ssm:COMMON_LIB_ARN_PYTHON}
    vpc:
      securityGroupIds:
        - ${ssm:SECURITY_GROUP_ID}
      subnetIds:
        - ${ssm:SUBNET_ID}
    events:
      - http:
          path: /otp-validation
          method: post
          cors: true

  view_lots:
    handler: handlers/view_list_lots.view_list_lots
    runtime: python3.8
    layers:
    - ${ssm:COMMON_LIB_ARN_PYTHON}
    vpc:
      securityGroupIds:
      - ${ssm:SECURITY_GROUP_ID}
      subnetIds:
      - ${ssm:SUBNET_ID}
    events:
      - http:
          cors: true
          path: /view-lots
          method: get
  
  search_lots:
    handler: handlers/search_lots.lot_search
    runtime: python3.8
    layers:
    - ${ssm:COMMON_LIB_ARN_PYTHON}
    vpc:
      securityGroupIds:
      - ${ssm:SECURITY_GROUP_ID}
      subnetIds:
      - ${ssm:SUBNET_ID}
    events:
      - http:
          cors: true
          path: /search-lots
          method: get

              
  view_lot_details:
    handler: handlers/view_lots.lot_details
    runtime: python3.8
    layers:
    - ${ssm:COMMON_LIB_ARN_PYTHON}
    vpc:
      securityGroupIds:
      - ${ssm:SECURITY_GROUP_ID}
      subnetIds:
      - ${ssm:SUBNET_ID}
    events:
      - http:
          cors: true
          path: /lot-details
          method: get
          
  credit_card:
    handler: handlers/credit_card.credit_card
    runtime: python3.8
    layers:
    - ${ssm:COMMON_LIB_ARN_PYTHON}
    vpc:
      securityGroupIds:
      - ${ssm:SECURITY_GROUP_ID}
      subnetIds:
      - ${ssm:SUBNET_ID}
    events:
      - http:
          cors: true
          path: /verify-card
          method: post

  acceting_buyer:
      handler: handlers/accept_buyer.accept_buyer
      runtime: python3.8
      layers:
      - ${ssm:COMMON_LIB_ARN_PYTHON}
      vpc:
        securityGroupIds:
        - ${ssm:SECURITY_GROUP_ID}
        subnetIds:
        - ${ssm:SUBNET_ID}
      events:
        - http:
            cors: true
            path: /approval
            method: patch
            authorizer:
              arn: ${ssm:SELLER_COGNITO_AUTH_ARN}
  
  update_password:
    handler: handlers/update_password.update_password
    runtime: python3.8
    layers:
    - ${ssm:COMMON_LIB_ARN_PYTHON}
    vpc:
      securityGroupIds:
      - ${ssm:SECURITY_GROUP_ID}
      subnetIds:
      - ${ssm:SUBNET_ID}
    events:
      - http:
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Requested-With
              - Accept
              - Access-Control-Allow-Headers
          authorizer: arn:aws:lambda:${env:REGION}:${ssm:ACCOUNT_ID}:function:lambda-authorizer-${self:provider.stage}-lambda-authorizer
          path: /update-password
          method: post
  


  auction_register:
    handler: handlers/register_auction.register_auction
    runtime: python3.8
    layers:
      - ${ssm:COMMON_LIB_ARN_PYTHON}
    vpc:
      securityGroupIds:
        - ${ssm:SECURITY_GROUP_ID}
      subnetIds:
        - ${ssm:SUBNET_ID}
    events:
      - http:
          path: /auction-register
          method: get
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Requested-With
              - Accept
              - Access-Control-Allow-Headers
          authorizer: arn:aws:lambda:${env:REGION}:${ssm:ACCOUNT_ID}:function:lambda-authorizer-${self:provider.stage}-lambda-authorizer

  view_profile:
    handler: handlers/view_profile.view_profile
    runtime: python3.8
    layers:
    - ${ssm:COMMON_LIB_ARN_PYTHON}
    vpc:
      securityGroupIds:
      - ${ssm:SECURITY_GROUP_ID}
      subnetIds:
      - ${ssm:SUBNET_ID}
    events:
      - http:
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Requested-With
              - Accept
              - Access-Control-Allow-Headers
          path: /profile
          method: patch
          authorizer: arn:aws:lambda:${env:REGION}:${ssm:ACCOUNT_ID}:function:lambda-authorizer-${self:provider.stage}-lambda-authorizer
  
  add_address:
    handler: handlers/add_address.add_address
    runtime: python3.8
    layers:
    - ${ssm:COMMON_LIB_ARN_PYTHON}
    vpc:
      securityGroupIds:
      - ${ssm:SECURITY_GROUP_ID}
      subnetIds:
      - ${ssm:SUBNET_ID}
    events:
      - http:
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Requested-With
              - Accept
              - Access-Control-Allow-Headers
          path: /add-address
          method: patch
          authorizer: arn:aws:lambda:${env:REGION}:${ssm:ACCOUNT_ID}:function:lambda-authorizer-${self:provider.stage}-lambda-authorizer
      
  paddle_number:
    handler: handlers/get_paddle.paddle_number
    runtime: python3.8
    layers:
    - ${ssm:COMMON_LIB_ARN_PYTHON}
    vpc:
      securityGroupIds:
      - ${ssm:SECURITY_GROUP_ID}
      subnetIds:
      - ${ssm:SUBNET_ID}
    events:
      - http:
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Requested-With
              - Accept
              - Access-Control-Allow-Headers
          path: /paddle
          method: get
          authorizer: arn:aws:lambda:${env:REGION}:${ssm:ACCOUNT_ID}:function:lambda-authorizer-${self:provider.stage}-lambda-authorizer


  send-reset-link:
    handler: handlers/send_reset_link.send_reset_link
    runtime: python3.8
    layers:
      - ${ssm:COMMON_LIB_ARN_PYTHON}
    vpc:
      securityGroupIds:
        - ${ssm:SECURITY_GROUP_ID}
      subnetIds:
        - ${ssm:SUBNET_ID}
    events:
      - http:
          cors: true
          path: /forgot_password
          method: post

  update-new-password:
    handler: handlers/reset.password_reset
    runtime: python3.8
    layers: 
      - ${ssm:COMMON_LIB_ARN_PYTHON}
      - ${ssm:COMMON_LIB_ARN_PYTHON_2}
    vpc:
        securityGroupIds:
          - ${ssm:SECURITY_GROUP_ID}
        subnetIds:
          - ${ssm:SUBNET_ID}
    events:
      - http:
          cors: true
          path: /reset_password
          method: post



resources:
   Resources:
    GatewayResponseDefault4XX:
       Type: 'AWS::ApiGateway::GatewayResponse'
       Properties:
         ResponseParameters:
           gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
           gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
         ResponseType: DEFAULT_4XX
         RestApiId:
           Ref: 'ApiGatewayRestApi'

    sesTemplate:
      Type: AWS::Pinpoint::EmailTemplate
      Properties:
        HtmlPart: ${file(./templates/paddle.html)}
        Subject: "{{subject}}"
        TemplateName: ${opt:stage, 'dev'}_paddle
          
plugins:
  - serverless-offline
  - serverless-package-external
  - serverless-domain-manager