service: bidding
frameworkVersion: "3"
useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  region: eu-west-2
  vpc:
    securityGroupIds:
      - sg-0882c1da39e729097
    subnetIds:
      - subnet-0ff05c7c2bd2a3f87
  websocketsApiName: ${self:provider.stage}-${self:service}-place-a-bid
  websocketsApiRouteSelectionExpression: $request.body.action # custom routes are selected by the value of the action property in the body
  websocketsDescription: Serverless Socket API for bidding flow
  environment:
    STAGE: ${self:provider.stage}
    REGION: eu-west-2
    END_POINT: https://api.indyauction.net/${self:provider.stage}/v1

    
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - states:*
            - dynamodb:*
            - lambda:*
            - cognito-idp:*
            - s3:*
            - execute-api:*
            - ses:*
          Resource: "*"

package:
  patterns:
    - "!./**"
    - "!./node_modules/**"
    - ./utils/**
    - ./handlers/**
    - ./assets/**
    - ../../lib/**
    - ../../entities/**

custom:
  packageExternal:
    external:
      - "../../lib"
      - "../../entities"
  customDomain:
    rest:
      domainName: ${env:DOMAIN_NAME}
      stage: ${opt:stage, self:provider.stage}
      basePath: ${opt:stage, self:provider.stage}/v1/${self:service}
      certificateName: ${env:DOMAIN_CERTIFICATE}
      createRoute53Record: true
      securityPolicy: tls_1_2
      endpointType: regional

functions:
  socket-connections-handler:
    handler: handlers/socket_connection_handler.handler
    layers:
      - arn:aws:lambda:eu-west-2:929441721738:layer:nodejs-indy-auction:12
    events:
      - websocket:
          route: $connect
      - websocket:
          route: $disconnect
      - websocket:
          route: $default

resources:
  Resources:
    GatewayResponseDefault4XX:
      Type: "AWS::ApiGateway::GatewayResponse"
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: DEFAULT_4XX
        RestApiId:
          Ref: "ApiGatewayRestApi"
 
plugins:
  - serverless-package-external
  - serverless-domain-manager
  - serverless-offline
