color: true
dry-run: null
hookfiles: hooks.py
language: python
require: null
server: null
server-wait: 3
init: false
custom: {}
names: false
only: []
reporter: ['html']
output: ['../../test-results/in-person-auctions-apis.html']
header:
  - "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64)"
sorted: false
user: null
inline-errors: false
details: false
method: []
loglevel: warning
path: []
hooksTimeout: 5000
hooks-worker-timeout: 50000
hooks-worker-connect-timeout: 1500
hooks-worker-connect-retry: 500
hooks-worker-after-connect-wait: 100
hooks-worker-term-timeout: 5000
hooks-worker-term-retry: 500
hooks-worker-handler-host: 127.0.0.1
hooks-worker-handler-port: 61321
config: ./dredd.yml 
blueprint: in-person-auction-management-swagger.json
endpoint: 'https://apis.dev.indyauction.net/v1/in-person-buyer'