service: payments
frameworkVersion: '3'
useDotenv: true
deprecationNotificationMode: error
disabledDeprecations:
  - UNSUPPORTED_CLI_OPTIONS
  - CLI_OPTIONS_SCHEMA_V3
  - CONFIG_VALIDATION_MODE_DEFAULT_V3
  - 
provider:
  name: aws
  endpointType: REGIONAL
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  region: ${env:REGION}
  versionFunctions: false
  layers: ${ssm:COMMON_LIB_ARN}
  environment:
    TABLE_NAME: ${opt:stage, self:provider.stage}-${self:service}
    COGNITO_USER_POOL_ID: ${ssm:SELLER_COGNITO_USERPOOL_ID}
    COGNITO_SELLER_CLIENT_ID: ${ssm:SELLER_COGNITO_CLIENT_ID}
    REGION: ${env:REGION}
    STAGE: ${opt:stage, self:provider.stage}
    DATABASE: indyauction-${opt:stage, self:provider.stage}
    MONGODB_NAME: indyauction-${opt:stage, self:provider.stage}
    MONGODB_COLLECTION_NAME: ${opt:stage, self:provider.stage}-users
    MONGO_CLIENT: ${ssm:MONGODB_CONNECTION_STRING}
    AUCTION_MONGODB_COLLECTION_NAME: ${opt:stage, self:provider.stage}-auctions
    COGNITO_USER_POOL: ${ssm:SELLER_COGNITO_USERPOOL_NAME}
    SELLERS_TABLE: ${opt:stage, self:provider.stage}-users
    SUMSUB_SECRET_KEY: ${env:SUMSUB_SECRET_KEY}
    SUMSUB_APP_TOKEN: ${env:SUMSUB_APP_TOKEN}
    CSV_FILE: ${env:CSV_FILE}
    S3_BUCKET:  ${ssm:BUCKET_NAME}
    LOT_COLLECTION_NAME: ${opt:stage, self:provider.stage}-lots
    COUNTER_LOT: ${opt:stage, self:provider.stage}-counters
    REGISTER_AUCTION_COLLECTION: ${opt:stage, self:provider.stage}-register-auction
    SUB_DOMAIN_TABLE: ${opt:stage, self:provider.stage}-subdomain
    USERPOOLS_MONGO: ${opt:stage, self:provider.stage}-userpools
    KMS_KEY_ID: ${ssm:KMS_KEY_ID}
    BUYER_EMAIL_OTP_TEMPLATE: 
      Fn::Join:
        - ":"
        - - "arn"
          - "aws"
          - "mobiletargeting"
          - !Ref "AWS::Region"
          - !Ref "AWS::AccountId"
          - "template/${self:provider.stage}-buyer_email_otp"
          - "EMAIL"
    ENCRYPTION_SECRET_KEY: ${env:ENCRYPTION_SECRET_KEY}
    BUYER_COLLECTION: ${opt:stage, self:provider.stage}-buyers
    RECAPTCHA_KEY: ${env:RECAPTCHA_KEY}
    RECAPTCHA_URL: ${env:RECAPTCHA_URL}
    CUSTOMER_SESSION_TOKEN_SECRET: ${env:CUSTOMER_SESSION_TOKEN_SECRET}
    SENDER_EMAIL_ADDRESS: ${ssm:SENDER_EMAIL}
    DEFAULT_SUB_DOMAIN: ${ssm:DEFAULT_SUB_DOMAIN}    
    JWT_SECRET_KEY: ${env:JWT_SECRET_KEY}
    TEMPLATE_ARN_EMAIL_RESET_PASSWORD:  
      Fn::Join:
        - ":"
        - - "arn"
          - "aws"
          - "mobiletargeting"
          - !Ref "AWS::Region"
          - !Ref "AWS::AccountId"
          - "template/${self:provider.stage}-buyer_reset_password"
          - "EMAIL"
   
    BASE_URL_BUYER: ${ssm:DEFAULT_SUB_DOMAIN}
    AMPLIFY_APP_ID: ${env:AMPLIFY_APP_ID}
    AMPLIFY_DOMAIN_NAME: ${ssm:AMPLIFY_DOMAIN_NAME}
    DEFAULT_INDENTITY_POOL_ID: ${ssm:BUYER_COGNITO_IDENTITY_POOL_ID}
    DEFAULT_IDENTITY_POOL_NAME: ${ssm:BUYER_COGNITO_IDENTITY_POOL_NAME}
    DEFAULT_BUYER_USERPOOL_ID: ${ssm:BUYER_COGNITO_USERPOOL_ID}
    SUBDOMAIN_COLLECTION: ${opt:stage, self:provider.stage}-subdomain
    AMPLIFY_BRANCH: ${env:AMPLIFY_BRANCH}
    STRIPE_API_KEY: ${env:STRIPE_API_KEY}
    PAYMENTS_COLLECTION: ${opt:stage, self:provider.stage}-buyers-payments
    STRIPE_ENDPOINT_SECRET: ${env:STRIPE_ENDPOINT_SECRET}
    ORDERS_COLLECTION: ${opt:stage, self:provider.stage}-orders
    ADDRESS_COLLECTION: ${opt:stage, self:provider.stage}-address-management
    CART_COLLECTION: ${opt:stage, self:provider.stage}-carts


    
  http:
    cors: true
     

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - cognito-idp:*
            - ses:*
            - s3:*
            - lambda:*
            - mobiletargeting:*
            - dynamodb:*
            - execute-api:*
            - amplify:*
            - route53:*
            - cognito-identity:UpdateIdentityPool
          Resource: "*"
 
package:
  patterns:
    - '!./node_modules/**'
    - ./handlers/**
    - ./data/**
    - ./entities/**
    - ./utils/**
    - ./lib/**

custom:
  packageExternal:
    external:
      - '../../lib'
      - '../../entities'
      
  customDomain:
    rest:
      domainName: ${ssm:DOMAIN_NAME}
      stage: ${opt:stage, self:provider.stage}
      basePath: v1/${self:service}
      certificateName: ${ssm:DOMAIN_CERTIFICATE}
      createRoute53Record: true
      securityPolicy: tls_1_2
      endpointType: REGIONAL

functions: 
  create_intent:
    handler: handlers/create.create_intent
    runtime: python3.8
    layers:
    - ${ssm:COMMON_LIB_ARN_PYTHON}
    vpc:
      securityGroupIds:
      - ${ssm:SECURITY_GROUP_ID}
      subnetIds:
      - ${ssm:SUBNET_ID}
    events:
      - http:
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Requested-With
              - Accept
              - Access-Control-Allow-Headers
          path: /stripe
          method: get
          authorizer: arn:aws:lambda:${env:REGION}:${ssm:ACCOUNT_ID}:function:lambda-authorizer-${self:provider.stage}-lambda-authorizer
  stripe_payments_webhook:
    handler: handlers/stripe_webhook.update
    runtime: python3.8
    layers:
    - ${ssm:COMMON_LIB_ARN_PYTHON}
    vpc:
      securityGroupIds:
      - ${ssm:SECURITY_GROUP_ID}
      subnetIds:
      - ${ssm:SUBNET_ID}
    events:
      - http:
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Requested-With
              - Accept
              - Access-Control-Allow-Headers
          path: /payments_webhook
          method: post


resources:
   Resources:
    GatewayResponseDefault4XX:
       Type: 'AWS::ApiGateway::GatewayResponse'
       Properties:
         ResponseParameters:
           gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
           gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
         ResponseType: DEFAULT_4XX
         RestApiId:
           Ref: 'ApiGatewayRestApi'
    # BuyerEmailOtp:
    #   Type: AWS::Pinpoint::EmailTemplate
    #   Properties: 
    #     HtmlPart: ${file(./templates/buyer_email_otp.html)}
    #     Subject: Indy.auction - OTP Verification for Your Account
    #     TemplateName: ${self:provider.stage}-buyer_email_otp
    
    # BuyerResetPassword:
    #   Type: AWS::Pinpoint::EmailTemplate
    #   Properties: 
    #     HtmlPart: ${file(./templates/buyer_reset_password.html)}
    #     Subject: Indy.auction- Reset your password
    #     TemplateName: ${self:provider.stage}-buyer_reset_password


plugins:
  - serverless-offline
  - serverless-package-external
  - serverless-domain-manager